import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ChevronDown, ChevronUp, Plus, Search } from 'lucide-react';
import { createCustomer, getCustomer, listCustomers, updateCustomer, type Customer, type CustomerInput, type CustomerListParams } from '../api/customers-api';
import { CustomerForm } from '../components/customer-form';
import { ApiError } from '@/shared/api/http';

const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none ring-blue-500 placeholder:text-slate-400 focus:ring-2';
const date = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' }).format(parsed); };

function paramsFromUrl(search: URLSearchParams): CustomerListParams { const active = search.get('active'); return { page: Math.max(1, Number(search.get('page') ?? 1) || 1), pageSize: Math.min(100, Math.max(1, Number(search.get('pageSize') ?? 20) || 20)), search: search.get('search') || undefined, active: active === null ? true : active === 'all' ? undefined : active === 'true', sort: (['createdAt', 'name', 'updatedAt'].includes(search.get('sort') ?? '') ? search.get('sort') : 'createdAt') as CustomerListParams['sort'], direction: search.get('direction') === 'desc' ? 'desc' : 'asc' }; }
function writeParams(params: CustomerListParams, set: (next: URLSearchParams) => void) { const next = new URLSearchParams(); next.set('page', String(params.page)); next.set('pageSize', String(params.pageSize)); if (params.search) next.set('search', params.search); next.set('active', params.active === undefined ? 'all' : String(params.active)); next.set('sort', params.sort); next.set('direction', params.direction); set(next); }
function PageHeader({ title, description, children }: { title: string; description?: string; children?: React.ReactNode }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{children}</div>; }
function ErrorState({ onRetry }: { onRetry: () => void }) { return <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center text-sm text-red-700">Não foi possível carregar os clientes.<button onClick={onRetry} className="ml-2 font-semibold underline">Tentar novamente</button></div>; }

export function CustomersListPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const params = useMemo(() => paramsFromUrl(searchParams), [searchParams]); const [searchInput, setSearchInput] = useState(params.search ?? '');
  const query = useQuery({ queryKey: ['customers', params], queryFn: () => listCustomers(params), placeholderData: (previous) => previous });
  useEffect(() => { setSearchInput(params.search ?? ''); }, [params.search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (searchInput !== (params.search ?? '')) writeParams({ ...params, search: searchInput.trim() || undefined, page: 1 }, setSearchParams); }, 300); return () => window.clearTimeout(timer); }, [searchInput]);
  function setParam(name: keyof CustomerListParams, value: string) { const next = { ...params, page: name === 'page' ? Number(value) : 1, [name]: value === 'all' ? undefined : name === 'active' ? value === 'true' : value }; writeParams(next, setSearchParams); }
  const totalPages = query.data?.meta.totalPages ?? 0;
  const customers = query.data?.data ?? [];
  return <><PageHeader title="Clientes" description="Gerencie os clientes da sua oficina."><Link to="/app/customers/new" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={17} />Novo cliente</Link></PageHeader>
    <div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Buscar por nome, documento ou telefone</span><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input className={`${inputClass} pl-10`} placeholder="Buscar por nome, documento ou telefone" value={searchInput} onChange={(e) => setSearchInput(e.target.value)} /></label><select aria-label="Situação" className={`${inputClass} lg:w-44`} value={params.active === undefined ? 'all' : String(params.active)} onChange={(e) => setParam('active', e.target.value)}><option value="true">Ativos</option><option value="all">Todos</option><option value="false">Inativos</option></select><select aria-label="Ordenar por" className={`${inputClass} lg:w-44`} value={params.sort} onChange={(e) => setParam('sort', e.target.value)}><option value="createdAt">Cadastro</option><option value="name">Nome</option><option value="updatedAt">Atualização</option></select><button type="button" aria-label="Alternar direção" title="Alternar direção" onClick={() => setParam('direction', params.direction === 'asc' ? 'desc' : 'asc')} className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-3 text-slate-600">{params.direction === 'asc' ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button></div>
      {query.isPending && !query.data ? <div role="status" className="space-y-3 py-8">{[1, 2, 3].map((item) => <div key={item} className="h-12 animate-pulse rounded-lg bg-slate-100" />)}</div> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : customers.length === 0 ? <div className="py-16 text-center"><p className="font-semibold text-slate-800">{params.search ? 'Nenhum cliente encontrado.' : 'Nenhum cliente cadastrado.'}</p><p className="mt-1 text-sm text-slate-500">{params.search ? 'Tente ajustar sua busca.' : 'Cadastre o primeiro cliente da sua oficina.'}</p>{!params.search && <Link to="/app/customers/new" className="mt-4 inline-flex rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Cadastrar cliente</Link>}</div> : <><div className="relative overflow-x-auto">{query.isFetching && <span role="status" className="absolute right-2 top-2 text-xs text-slate-400">Atualizando…</span>}<table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Nome</th><th className="px-3 py-3">Documento</th><th className="px-3 py-3">Telefone</th><th className="px-3 py-3">E-mail</th><th className="px-3 py-3">Situação</th><th className="px-3 py-3">Cadastro</th><th className="px-3 py-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{customers.map((customer) => <CustomerRow key={customer.id} customer={customer} />)}</tbody></table></div><div className="flex flex-col gap-3 border-t border-slate-100 pt-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>{query.data?.meta.total ?? 0} clientes</span><div className="flex items-center gap-2"><button disabled={params.page <= 1} onClick={() => setParam('page', String(params.page - 1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span>Página {params.page} de {Math.max(1, totalPages)}</span><button disabled={params.page >= totalPages} onClick={() => setParam('page', String(params.page + 1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div></>}</div></>;
}
function CustomerRow({ customer }: { customer: Customer }) { return <tr><td className="px-3 py-4 font-medium text-slate-900">{customer.name}</td><td className="px-3 py-4">{customer.document || '—'}</td><td className="px-3 py-4">{customer.phone}</td><td className="px-3 py-4">{customer.email || '—'}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${customer.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{customer.active ? 'Ativo' : 'Inativo'}</span></td><td className="px-3 py-4">{date(customer.createdAt)}</td><td className="px-3 py-4"><Link to={`/app/customers/${customer.id}`} className="font-semibold text-blue-700 hover:underline">Visualizar</Link></td></tr>; }

export function NewCustomerPage() { const navigate = useNavigate(); const client = useQueryClient(); const mutation = useMutation({ mutationFn: createCustomer, onSuccess: async (customer) => { await client.invalidateQueries({ queryKey: ['customers'] }); navigate(`/app/customers/${customer.id}`, { state: { saved: 'Cliente cadastrado com sucesso.' } }); } }); return <CustomerEditor title="Novo cliente" description="Cadastre um cliente para sua oficina." submitting={mutation.isPending} onSubmit={(value) => mutation.mutateAsync(value)} onCancel={() => navigate('/app/customers')} />; }
export function EditCustomerPage() { const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const customer = useQuery({ queryKey: ['customer', id], queryFn: () => getCustomer(id) }); const mutation = useMutation({ mutationFn: (value: Partial<CustomerInput>) => updateCustomer(id, value), onSuccess: async (saved) => { await client.invalidateQueries({ queryKey: ['customers'] }); await client.invalidateQueries({ queryKey: ['customer', id] }); navigate(`/app/customers/${saved.id}`, { state: { saved: 'Cliente atualizado com sucesso.' } }); } }); if (customer.isPending) return <div role="status">Carregando cliente…</div>; if (customer.isError || !customer.data) return <ErrorState onRetry={() => void customer.refetch()} />; const initial = { name: customer.data.name, document: customer.data.document ?? '', phone: customer.data.phone, email: customer.data.email ?? '', notes: customer.data.notes ?? '' }; const submitChanges = (value: CustomerInput) => { const current = { name: customer.data.name, document: customer.data.document ?? '', phone: customer.data.phone, email: customer.data.email ?? '', notes: customer.data.notes ?? '' }; const changed = Object.fromEntries(Object.entries(value).filter(([field, next]) => next !== current[field as keyof typeof current])); return mutation.mutateAsync(changed); }; return <CustomerEditor title="Editar cliente" description="Atualize os dados cadastrais." initial={initial} submitting={mutation.isPending} omitEmptyOptional={false} onSubmit={submitChanges} onCancel={() => navigate(`/app/customers/${id}`)} />; }
function CustomerEditor({ title, description, initial, submitting, omitEmptyOptional, onSubmit, onCancel }: { title: string; description: string; initial?: Partial<CustomerInput>; submitting: boolean; omitEmptyOptional?: boolean; onSubmit: (value: CustomerInput) => Promise<unknown>; onCancel: () => void }) { return <div className="mx-auto max-w-3xl"><PageHeader title={title} description={description} /><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><CustomerForm initial={initial} submitting={submitting} omitEmptyOptional={omitEmptyOptional} onSubmit={onSubmit} onCancel={onCancel} /></div></div>; }

export function CustomerDetailPage() { const { id = '' } = useParams(); const navigate = useNavigate(); const location = window.history.state?.usr as { saved?: string } | undefined; const query = useQuery({ queryKey: ['customer', id], queryFn: () => getCustomer(id) }); if (query.isPending) return <div role="status">Carregando cliente…</div>; if (query.isError || !query.data) return <ErrorState onRetry={() => void query.refetch()} />; const customer = query.data; return <><Link to="/app/customers" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft size={16} />Voltar para Clientes</Link><PageHeader title={customer.name} description="Detalhes do cliente"><button onClick={() => navigate('edit')} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Editar</button></PageHeader>{location?.saved && <div role="status" className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{location.saved}</div>}<div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h3 className="font-semibold text-slate-900">Dados cadastrais e contato</h3><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[['Nome', customer.name], ['Documento', customer.document || 'Não informado'], ['Telefone', customer.phone], ['E-mail', customer.email || 'Não informado'], ['Cadastrado em', date(customer.createdAt)], ['Atualizado em', date(customer.updatedAt)]].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value}</dd></div>)}</dl></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-semibold text-slate-900">Situação</h3><p className="mt-3"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{customer.active ? 'Ativo' : 'Inativo'}</span></p></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><h3 className="font-semibold text-slate-900">Observações</h3><p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{customer.notes || 'Nenhuma observação cadastrada.'}</p></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold text-slate-900">Veículos</h3><p className="mt-2 text-sm text-slate-500">Consulte os veículos vinculados a este cliente.</p></div><Link to={`/app/vehicles?customerId=${customer.id}`} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-semibold text-blue-700">Ver veículos</Link></div></section></div></>; }
