import { httpClient } from '@/shared/api/http';
import type { DocumentItem, ItemInput, Page } from '@/features/quotes/api/quotes-api';
import { normalizeMoney } from '@/features/shared/money';
export type WorkOrderStatus = 'OPEN' | 'WAITING_APPROVAL' | 'IN_PROGRESS' | 'WAITING_PARTS' | 'COMPLETED' | 'DELIVERED' | 'CANCELLED';
export type WorkOrderStockOption = { id: string; productId: string; availableQuantity: number; origin: 'PURCHASE' | 'OPENING'; unitCost: string | null; purchaseDate: string | null; supplier: { id: string; name: string } | null; purchase: { id: string; documentNumber: string | null } | null; batchNumber: string | null; warrantyDays: number };
export type WorkOrderStockAllocation = { id: string; workOrderItemId: string; stockEntryId: string | null; quantity: number; unitCost: string | null; stockEntry: { supplier: { name: string } | null; purchase: { id: string; documentNumber: string | null } | null; batchNumber: string | null; warrantyExpiry: string | null } | null };
export type WorkOrder = { id: string; number: number; customerId: string; vehicleId: string; customer?: { name: string }; vehicle?: { plate: string; brand: string; model: string }; quoteId: string | null; status: WorkOrderStatus; reportedProblem: string | null; diagnosis: string | null; mileage: number | null; expectedCompletionDate: string | null; notes: string | null; items: DocumentItem[]; stockOptions?: WorkOrderStockOption[]; stockAllocations?: WorkOrderStockAllocation[]; total: string; createdAt: string; updatedAt: string };
export type WorkOrderFinancial = WorkOrder & { financial: { total: string; paid: string; discount: string; balance: string; status: 'UNPAID' | 'PARTIAL' | 'PAID' } };
export type WorkOrderInput = { customerId: string; vehicleId: string; reportedProblem?: string; diagnosis?: string; mileage?: number; expectedCompletionDate?: string; notes?: string; items?: ItemInput[] };
export const listWorkOrders = (params: Record<string, unknown>) => httpClient.get<Page<WorkOrder>>('/work-orders', { params }).then((r) => r.data);
export const listFinancialWorkOrders = (params: Record<string, unknown>) => httpClient.get<Page<WorkOrderFinancial>>('/work-orders/financial', { params }).then((r) => r.data);
export const getWorkOrder = (id: string) => httpClient.get<WorkOrder>(`/work-orders/${id}`).then((r) => r.data);
export const createWorkOrder = (input: WorkOrderInput) => httpClient.post<WorkOrder>('/work-orders', input).then((r) => r.data);
export const convertQuote = (quoteId: string) => httpClient.post<WorkOrder>(`/work-orders/from-quote/${quoteId}`).then((r) => r.data);
export const updateWorkOrder = (id: string, input: Partial<WorkOrderInput>) => httpClient.patch<WorkOrder>(`/work-orders/${id}`, input).then((r) => r.data);
const normalizeItem = <T extends ItemInput | Partial<ItemInput>>(input: T): T => input.unitPrice === undefined ? input : { ...input, unitPrice: normalizeMoney(input.unitPrice) } as T;
export const addWorkOrderItem = (id: string, input: ItemInput) => httpClient.post<WorkOrder>(`/work-orders/${id}/items`, normalizeItem(input)).then((r) => r.data);
export const updateWorkOrderItem = (id: string, itemId: string, input: Partial<ItemInput>) => httpClient.patch<WorkOrder>(`/work-orders/${id}/items/${itemId}`, normalizeItem(input)).then((r) => r.data);
export const removeWorkOrderItem = (id: string, itemId: string) => httpClient.delete<WorkOrder>(`/work-orders/${id}/items/${itemId}`).then((r) => r.data);
export type WorkOrderAllocationInput = { workOrderItemId: string; stockEntryId?: string; quantity: number };
export const workOrderAction = (id: string, action: 'request-approval' | 'start' | 'wait-parts' | 'complete' | 'deliver' | 'cancel', body?: { allocations?: WorkOrderAllocationInput[] }) => (body === undefined ? httpClient.post<WorkOrder>(`/work-orders/${id}/${action}`) : httpClient.post<WorkOrder>(`/work-orders/${id}/${action}`, body)).then((r) => r.data);
