import { useQuery } from '@tanstack/react-query';
import { RefreshCw } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { fetchDashboard, fetchRecentAuditEvents, type DashboardData } from '@/features/dashboard/api/dashboard-api';
import { formatPlatformMoney, formatPlatformTimestamp } from '@/features/platform/platform-formatters';
import { PlatformEmpty, PlatformError, PlatformLoading, PlatformSection } from '@/features/platform/components/platform-primitives';

const labels: Record<string, string> = { 'commercial_account.created': 'Conta comercial criada', 'organization.created': 'Oficina criada', 'organization.updated': 'Oficina atualizada', 'organization.activated': 'Oficina ativada', 'organization.deactivated': 'Oficina desativada', 'organization.suspended': 'Oficina suspensa', 'organization.reactivated': 'Oficina reativada', 'subscription.created': 'Assinatura criada', 'subscription.cancelled': 'Assinatura cancelada', 'subscription_charge.created': 'Cobrança criada', 'charge_settlement.created': 'Recebimento registrado' };
const monthName = (month: string) => { const [year, value] = month.split('-'); return new Intl.DateTimeFormat('pt-BR', { month: 'short', timeZone: 'UTC' }).format(new Date(Date.UTC(Number(year), Number(value) - 1, 1))).replace('.', ''); };

export function PlatformHomePage() {
  const [search, setSearch] = useSearchParams();
  const dashboard = useQuery({ queryKey: ['platform-dashboard', search.get('from'), search.get('to')], queryFn: () => fetchDashboard({ from: search.get('from') ?? undefined, to: search.get('to') ?? undefined }), refetchOnMount: 'always' });
  const events = useQuery({ queryKey: ['platform-dashboard-audit'], queryFn: fetchRecentAuditEvents, refetchOnMount: 'always' });
  const setPeriod = (key: 'from' | 'to', value: string) => { const next = new URLSearchParams(search); value ? next.set(key, value) : next.delete(key); setSearch(next); };
  return <section aria-labelledby="platform-dashboard-title" className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wide text-violet-700">Visão comercial</p><h2 id="platform-dashboard-title" className="mt-2 text-3xl font-bold tracking-tight">Dashboard</h2><p className="mt-2 text-slate-600">Acompanhe a saúde operacional, comercial e financeira da plataforma.</p></div><div className="flex items-end gap-2"><label className="text-xs font-semibold text-slate-600">De<input aria-label="Mês inicial" type="month" value={search.get('from') ?? ''} onChange={(e) => setPeriod('from', e.target.value)} className="mt-1 block rounded-lg border border-slate-300 px-2 py-2 text-sm" /></label><label className="text-xs font-semibold text-slate-600">Até<input aria-label="Mês final" type="month" value={search.get('to') ?? ''} onChange={(e) => setPeriod('to', e.target.value)} className="mt-1 block rounded-lg border border-slate-300 px-2 py-2 text-sm" /></label><button type="button" onClick={() => { void dashboard.refetch(); void events.refetch(); }} className="rounded-lg border border-slate-300 p-2.5 text-slate-600" aria-label="Atualizar dashboard"><RefreshCw size={18} aria-hidden="true" /></button></div></div>{dashboard.isLoading ? <PlatformLoading label="Carregando indicadores…" /> : dashboard.isError ? <PlatformError error={dashboard.error} onRetry={() => void dashboard.refetch()} /> : dashboard.data && <DashboardContent data={dashboard.data} />}<PlatformSection title="Atividade administrativa recente">{events.isLoading ? <PlatformLoading label="Carregando atividades…" /> : events.isError ? <PlatformError error={events.error} onRetry={() => void events.refetch()} /> : events.data?.length ? <div className="divide-y divide-slate-100">{events.data.map((event) => <div key={event.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><div><p className="font-medium">{labels[event.action] ?? `Ação (${event.action})`}</p><p className="text-xs text-slate-500">{event.actor.name ?? 'Sistema'} · {event.target.type} · {formatPlatformTimestamp(event.occurredAt)}</p></div>{event.reason && <span className="max-w-xs text-xs text-slate-500">{event.reason}</span>}</div>)}</div> : <PlatformEmpty title="Nenhuma atividade recente" description="As atividades administrativas aparecerão aqui." />}</PlatformSection></section>;
}
function DashboardContent({ data }: { data: DashboardData }) { const cards = [['Organizations', data.organizations.total.toString(), 'Total de oficinas'], ['Contas comerciais novas', data.monthly.newCommercialAccounts.toString(), 'No mês de referência'], ['MRR', formatPlatformMoney(data.financial.mrr), 'Receita recorrente atual'], ['Receita recebida', formatPlatformMoney(data.financial.receivedRevenue), 'No mês de referência']]; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, detail]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>)}</div><div className="grid gap-6 xl:grid-cols-2"><PlatformSection title="Organizations"><MetricList values={[["Ativas", data.organizations.active], ["Inativas", data.organizations.inactive], ["Suspensas", data.organizations.suspended], ["Bloqueadas comercialmente", data.organizations.commerciallyBlocked], ["Novas no mês", data.monthly.newOrganizations]]} /></PlatformSection><PlatformSection title="Subscriptions"><MetricList values={[["Trial Period", data.subscriptions.trial], ["Pagas atuais", data.subscriptions.paidCurrent], ["Aguardando primeiro pagamento", data.subscriptions.awaitingFirstPayment], ["Inadimplentes", data.subscriptions.delinquent], ["Canceladas efetivas", data.subscriptions.effectivelyCancelled], ["Setup comercial pendente", data.subscriptions.pendingCommercialSetup]]} /></PlatformSection></div><PlatformSection title="Receita"><div className="grid gap-4 sm:grid-cols-3"><MoneyMetric label="Pendente total" value={data.financial.pendingRevenue.total} /><MoneyMetric label="Pendente próximo" value={data.financial.pendingRevenue.upcoming} /><MoneyMetric label="Pendente vencido" value={data.financial.pendingRevenue.overdue} /></div><p className="mt-4 text-xs text-slate-500">Valores pendentes classificados em próximos e vencidos.</p></PlatformSection><div className="grid gap-6 xl:grid-cols-2"><SeriesChart title="Evolução de Organizations" data={data.series.map((p) => ({ label: p.month, value: p.organizations, display: String(p.organizations) }))} /><SeriesChart title="Evolução do MRR" data={data.series.map((p) => ({ label: p.month, value: Number(p.mrr), display: formatPlatformMoney(p.mrr) }))} /></div></>; }
function MetricList({ values }: { values: Array<[string, number]> }) { return <dl className="grid grid-cols-2 gap-4">{values.map(([label, value]) => <div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>)}</dl>; }
function MoneyMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{formatPlatformMoney(value)}</p></div>; }
function SeriesChart({ title, data }: { title: string; data: Array<{ label: string; value: number; display: string }> }) { const max = Math.max(...data.map((p) => p.value), 1); const points = data.map((p, i) => `${(i / Math.max(data.length - 1, 1)) * 96 + 2},${38 - (p.value / max) * 32}`).join(' '); return <PlatformSection title={title}>{data.length === 0 ? <PlatformEmpty title="Sem histórico" description="Não há dados para o período selecionado." /> : <><svg role="img" aria-label={`${title}. ${data.map((p) => `${monthName(p.label)}: ${p.display}`).join('; ')}`} viewBox="0 0 100 42" className="h-40 w-full"><polyline fill="none" stroke="currentColor" strokeWidth="1.5" points={points} className="text-violet-600" />{data.map((p, i) => <circle key={p.label} cx={(i / Math.max(data.length - 1, 1)) * 96 + 2} cy={38 - (p.value / max) * 32} r="1.7" className="fill-violet-600"><title>{monthName(p.label)}: {p.display}</title></circle>)}</svg><div className="mt-3 flex justify-between text-xs text-slate-500"><span>{monthName(data[0].label)}</span><span>{monthName(data[data.length - 1].label)}</span></div></>}</PlatformSection>; }
