import { useQuery } from '@tanstack/react-query';
import { RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fetchDashboard, type DashboardData } from '@/features/dashboard/api/dashboard-api';
import { formatPlatformMoney } from '@/features/platform/platform-formatters';
import { PlatformEmpty, PlatformError, PlatformLoading } from '@/features/platform/components/platform-primitives';

export function PlatformHomePage() {
  const dashboard = useQuery({ queryKey: ['platform-dashboard'], queryFn: () => fetchDashboard({}), refetchOnMount: 'always' });
  return <section aria-labelledby="platform-dashboard-title" className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wide text-violet-700">Visão comercial</p><h2 id="platform-dashboard-title" className="mt-2 text-3xl font-bold tracking-tight">Visão geral</h2><p className="mt-2 text-slate-600">Acompanhe as oficinas, os recebimentos e a inadimplência da plataforma.</p></div><button type="button" onClick={() => void dashboard.refetch()} className="self-start rounded-lg border border-slate-300 p-2.5 text-slate-600 sm:self-auto" aria-label="Atualizar dashboard"><RefreshCw size={18} aria-hidden="true" /></button></div>{dashboard.isLoading ? <PlatformLoading label="Carregando indicadores…" /> : dashboard.isError ? <PlatformError error={dashboard.error} onRetry={() => void dashboard.refetch()} /> : dashboard.data && <DashboardContent data={dashboard.data} />}</section>;
}

function DashboardContent({ data }: { data: DashboardData }) {
  const referenceMonth = new Intl.DateTimeFormat('pt-BR', { month: '2-digit', year: 'numeric', timeZone: 'America/Recife' }).format(new Date(data.referenceAt));
  const cards = [['Total de oficinas', data.organizations.total.toString()], ['Em dia', data.organizations.current.toString()], ['Vence em breve', data.organizations.dueSoon.toString()], ['Em atraso', data.organizations.overdue.toString()], ['Bloqueadas por pagamento', data.organizations.paymentBlocked.toString()], ['Suspensas administrativamente', data.organizations.suspended.toString()]];
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">Situação na referência {referenceMonth}</p></div>)}</div><section aria-labelledby="revenue-title" className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 id="revenue-title" className="text-base font-semibold">Receita do mês</h3><div className="mt-5 grid gap-4 sm:grid-cols-3"><MoneyMetric label="Recebida" value={data.financial.receivedRevenue} /><MoneyMetric label="Em aberto no prazo" value={data.financial.openWithinDue} /><MoneyMetric label="Vencida" value={data.financial.overdue} /></div><p className="mt-4 text-xs text-slate-500">Valores calculados em {data.timezone}. Competência: {referenceMonth}.</p></section><section aria-labelledby="attention-title" className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 id="attention-title" className="text-base font-semibold">Oficinas que exigem atenção</h3>{data.attentionOrganizations.length ? <div className="mt-4 divide-y divide-slate-100">{data.attentionOrganizations.map((organization) => <div key={organization.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{organization.name}</p><p className="text-xs text-slate-500">{organization.reasons.map(reasonLabel).join(' · ')}</p></div><Link to={`/platform/organizations/${organization.id}`} className="text-sm font-semibold text-violet-700 hover:underline">Ver detalhe</Link></div>)}</div> : <div className="mt-4"><PlatformEmpty title="Nenhuma oficina exige atenção" description="Não há vencimentos críticos ou suspensões na referência." /></div>}</section></>;
}

function reasonLabel(reason: string) { return ({ DUE_SOON: 'Vence em breve', OVERDUE: 'Em atraso', PAYMENT_BLOCKED: 'Bloqueada por pagamento', SUSPENDED: 'Suspensa administrativamente' } as Record<string, string>)[reason] ?? reason; }
function MoneyMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{formatPlatformMoney(value)}</p></div>; }
