import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { AuthenticatedPrincipal } from '../auth/authenticated-principal';
import { PrismaService } from '../prisma/prisma.service';
import { ConfirmDirectSaleDto, CreateDirectSaleDto, DirectSaleItemDto, SalePaymentDto } from './dto/create-direct-sale.dto';
import { ListDirectSalesDto } from './dto/list-direct-sales.dto';

const cents = (value: string): bigint => { const [whole, fraction = ''] = value.split('.'); return BigInt(whole) * 100n + BigInt((fraction + '00').slice(0, 2)); };
const money = (value: bigint): string => `${value / 100n}.${(value % 100n).toString().padStart(2, '0')}`;
const include = {
  customer: { select: { id: true, name: true } },
  items: { orderBy: { createdAt: 'asc' as const } },
  payments: { orderBy: { createdAt: 'asc' as const } },
  stockAllocations: { include: { stockEntry: { include: { supplier: { select: { id: true, name: true } }, purchase: { select: { id: true, documentNumber: true } } } } } },
} as const;

@Injectable()
export class DirectSalesService {
  constructor(private readonly prisma: PrismaService) {}
  private tenant(p: AuthenticatedPrincipal) { if (p.role !== 'ADMIN' || !p.organizationId) throw new ForbiddenException('Organization Admin access required'); return p.organizationId; }
  private total(items: Array<{ quantity: number; unitPrice: string | Prisma.Decimal; discount?: string | Prisma.Decimal }>) { return items.reduce((s, i) => s + cents(i.unitPrice.toString()) * BigInt(i.quantity) - cents((i.discount ?? '0').toString()), 0n); }
  private format(row: any) {
    const total = this.total(row.items ?? []); const paid = (row.payments ?? []).filter((p: any) => p.status === 'CONFIRMED').reduce((s: bigint, p: any) => s + cents(p.amount.toString()), 0n);
    return { ...row, total: money(total), items: row.items?.map((i: any) => ({ ...i, unitPrice: money(cents(i.unitPrice.toString())), discount: money(cents(i.discount.toString())), lineTotal: money(cents(i.unitPrice.toString()) * BigInt(i.quantity) - cents(i.discount.toString())) })), payments: row.payments?.map((p: any) => ({ ...p, amount: money(cents(p.amount.toString())) })), financial: { total: money(total), paid: money(paid), balance: money(total - paid), status: paid === 0n ? 'UNPAID' : paid < total ? 'PARTIAL' : 'PAID' }, stockAllocations: row.stockAllocations?.map((a: any) => ({ ...a, unitCost: a.unitCost?.toString() ?? null, origin: a.stockEntry ? 'PURCHASE' : 'OPENING', supplier: a.stockEntry?.supplier ?? null, purchase: a.stockEntry?.purchase ?? null, warrantyDays: a.stockEntry?.warrantyDays ?? 0 })) };
  }
  private async resolveItems(tx: Prisma.TransactionClient, organizationId: string, items: DirectSaleItemDto[]) {
    if (!items.length) throw new BadRequestException('Direct Sale must have at least one Product');
    if (new Set(items.map(i => i.productId)).size !== items.length) throw new BadRequestException('A Product can appear only once in a Direct Sale');
    const products = await tx.product.findMany({ where: { organizationId, id: { in: items.map(i => i.productId) }, active: true }, select: { id: true, name: true, description: true, sku: true, salePrice: true } });
    if (products.length !== items.length) throw new NotFoundException('Active Product not found');
    return items.map(i => { const p = products.find(x => x.id === i.productId)!; const discount = i.discount ?? '0.00'; if (cents(discount) > cents(i.unitPrice) * BigInt(i.quantity)) throw new BadRequestException('Discount cannot exceed the line value'); return { productId: p.id, productName: p.name, sku: p.sku, quantity: i.quantity, unitPrice: i.unitPrice, discount }; });
  }
  async create(p: AuthenticatedPrincipal, dto: CreateDirectSaleDto) { const organizationId = this.tenant(p); return this.prisma.$transaction(async tx => { if (dto.customerId && !(await tx.customer.findFirst({ where: { id: dto.customerId, organizationId, active: true } }))) throw new NotFoundException('Customer not found'); const items = await this.resolveItems(tx, organizationId, dto.items); const counter = await tx.organization.update({ where: { id: organizationId }, data: { nextDirectSaleNumber: { increment: 1 } }, select: { nextDirectSaleNumber: true } }); const sale = await tx.directSale.create({ data: { organizationId, customerId: dto.customerId, number: counter.nextDirectSaleNumber - 1 } }); await tx.directSaleItem.createMany({ data: items.map(i => ({ organizationId, directSaleId: sale.id, ...i })) }); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id: sale.id }, include })); }); }
  async update(p: AuthenticatedPrincipal, id: string, dto: CreateDirectSaleDto) { const organizationId = this.tenant(p); return this.prisma.$transaction(async tx => { const current = await tx.directSale.findFirst({ where: { id, organizationId }, select: { status: true } }); if (!current) throw new NotFoundException('Direct Sale not found'); if (current.status !== 'DRAFT') throw new ConflictException('Only draft Direct Sales can be edited'); if (dto.customerId && !(await tx.customer.findFirst({ where: { id: dto.customerId, organizationId, active: true } }))) throw new NotFoundException('Customer not found'); const items = await this.resolveItems(tx, organizationId, dto.items); await tx.directSaleItem.deleteMany({ where: { organizationId, directSaleId: id } }); await tx.directSale.update({ where: { organizationId_id: { organizationId, id } }, data: { customerId: dto.customerId } }); await tx.directSaleItem.createMany({ data: items.map(i => ({ organizationId, directSaleId: id, ...i })) }); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id }, include })); }); }
  private async state(tx: Prisma.TransactionClient, organizationId: string, id: string) { await tx.$queryRaw`SELECT "id" FROM "DirectSale" WHERE "id" = ${id}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`; const sale = await tx.directSale.findFirst({ where: { id, organizationId }, include: { items: true, payments: true } }); if (!sale) throw new NotFoundException('Direct Sale not found'); const total = this.total(sale.items); const paid = sale.payments.filter(x => x.status === 'CONFIRMED').reduce((s, x) => s + cents(x.amount.toString()), 0n); return { sale, total, paid, balance: total - paid }; }
  private async addPayments(tx: Prisma.TransactionClient, organizationId: string, id: string, payments: SalePaymentDto[]) { for (const p of payments) await tx.salePayment.create({ data: { organizationId, directSaleId: id, amount: p.amount, method: p.method, status: p.status ?? 'CONFIRMED', paidAt: p.paidAt ? new Date(p.paidAt) : (p.status === 'PENDING' ? null : new Date()), installmentDueDate: p.installmentDueDate ? new Date(p.installmentDueDate) : null } }); }
  async confirm(p: AuthenticatedPrincipal, id: string, dto: ConfirmDirectSaleDto) { const organizationId = this.tenant(p); return this.prisma.$transaction(async tx => { const before = await this.state(tx, organizationId, id); if (before.sale.status !== 'DRAFT') throw new ConflictException('Only draft Direct Sales can be confirmed'); await this.addPayments(tx, organizationId, id, dto.payments ?? []); const state = await this.state(tx, organizationId, id); if (!state.sale.customerId && state.balance !== 0n) throw new ConflictException('Customer is required for a sale with pending balance or installments'); if (state.paid > state.total) throw new ConflictException('Sale payments exceed the balance'); for (const item of state.sale.items) { const locked = await tx.$queryRaw<Array<{ stockQuantity: number }>>`SELECT "stockQuantity" FROM "Product" WHERE "id" = ${item.productId}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`; if (!locked.length || locked[0].stockQuantity < item.quantity) throw new ConflictException(`Insufficient stock for Product ${item.sku}`); await tx.product.update({ where: { organizationId_id: { organizationId, id: item.productId } }, data: { stockQuantity: { decrement: item.quantity } } }); await tx.stockMovement.create({ data: { organizationId, productId: item.productId, directSaleId: id, type: 'CONSUMPTION', quantityChange: -item.quantity, note: `Direct Sale #${state.sale.number}` } }); let remaining = item.quantity; const entries = await tx.stockEntry.findMany({ where: { organizationId, productId: item.productId, status: 'AVAILABLE', quantity: { gt: 0 } }, orderBy: { createdAt: 'asc' } }); for (const entry of entries) { if (!remaining) break; const available = entry.quantity - entry.consumedQuantity; if (available <= 0) continue; const amount = Math.min(remaining, available); await tx.stockEntry.update({ where: { id: entry.id }, data: { consumedQuantity: { increment: amount } } }); await tx.directSaleStockAllocation.create({ data: { organizationId, directSaleId: id, directSaleItemId: item.id, stockEntryId: entry.id, quantity: amount, unitCost: entry.unitCost } }); remaining -= amount; } if (remaining) await tx.directSaleStockAllocation.create({ data: { organizationId, directSaleId: id, directSaleItemId: item.id, quantity: remaining } }); }
      await tx.directSale.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CONFIRMED', confirmedAt: new Date() } }); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id }, include })); }); }
  async addPayment(p: AuthenticatedPrincipal, id: string, dto: SalePaymentDto) { const organizationId = this.tenant(p); return this.prisma.$transaction(async tx => { const state = await this.state(tx, organizationId, id); if (state.sale.status !== 'CONFIRMED') throw new ConflictException('Only confirmed Direct Sales can receive payments'); if (!state.sale.customerId) throw new ConflictException('A sale without Customer is already settled'); if ((dto.status ?? 'CONFIRMED') === 'CONFIRMED' && cents(dto.amount) > state.balance) throw new ConflictException('Payment exceeds the Direct Sale balance'); await this.addPayments(tx, organizationId, id, [dto]); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id }, include })); }); }
  async list(p: AuthenticatedPrincipal, q: ListDirectSalesDto) { const organizationId = this.tenant(p); const page = q.page ?? 1, pageSize = q.pageSize ?? 20, search = q.search?.trim(); const number = search && /^\d+$/.test(search) ? Number(search) : undefined; const where: Prisma.DirectSaleWhereInput = { organizationId, ...(q.status ? { status: q.status as any } : {}), ...(search ? { OR: [...(number === undefined ? [] : [{ number }]), { customer: { name: { contains: search, mode: 'insensitive' } } }] } : {}) }; const [rows, total] = await this.prisma.$transaction([this.prisma.directSale.findMany({ where, include, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], skip: (page - 1) * pageSize, take: pageSize }), this.prisma.directSale.count({ where })]); return { data: rows.map(x => this.format(x)), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findOne(p: AuthenticatedPrincipal, id: string) { const row = await this.prisma.directSale.findFirst({ where: { id, organizationId: this.tenant(p) }, include }); if (!row) throw new NotFoundException('Direct Sale not found'); return this.format(row); }
  async receipt(p: AuthenticatedPrincipal, id: string) { const sale = await this.findOne(p, id); if (sale.status !== 'CONFIRMED') throw new ConflictException('Receipt is available only for confirmed Direct Sales'); return { type: 'DIRECT_SALE_RECEIPT', fiscal: false, issuedAt: new Date().toISOString(), sale }; }
  async cancel(p: AuthenticatedPrincipal, id: string) { const organizationId = this.tenant(p); return this.prisma.$transaction(async tx => { const sale = await tx.directSale.findFirst({ where: { id, organizationId }, include: { items: true, stockAllocations: true } }); if (!sale) throw new NotFoundException('Direct Sale not found'); if (sale.status === 'CANCELLED') throw new ConflictException('Direct Sale is already cancelled'); if (sale.status === 'DRAFT') { await tx.directSale.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CANCELLED', cancelledAt: new Date() } }); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id }, include })); } for (const a of sale.stockAllocations) { if (a.stockEntryId) await tx.stockEntry.update({ where: { id: a.stockEntryId }, data: { consumedQuantity: { decrement: a.quantity } } }); await tx.product.update({ where: { organizationId_id: { organizationId, id: sale.items.find(i => i.id === a.directSaleItemId)!.productId } }, data: { stockQuantity: { increment: a.quantity } } }); } await tx.salePayment.updateMany({ where: { organizationId, directSaleId: id, status: { not: 'CANCELLED' } }, data: { status: 'CANCELLED' } }); await tx.stockMovement.createMany({ data: sale.items.map(i => ({ organizationId, productId: i.productId, directSaleId: id, type: 'ADJUSTMENT' as const, quantityChange: i.quantity, note: `Estorno da Direct Sale #${sale.number}` })) }); await tx.directSale.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CANCELLED', cancelledAt: new Date() } }); return this.format(await tx.directSale.findFirstOrThrow({ where: { organizationId, id }, include })); }); }
}
