import { httpClient } from '@/shared/api/http';

export type OrganizationAdmin = { id: string; name: string; email: string; status: string };
export type FinancialStandingStatus = 'CURRENT' | 'DUE_SOON' | 'OVERDUE' | 'PAYMENT_BLOCKED';
export type Organization = { id: string; name: string; document?: string | null; phone?: string | null; email?: string | null; addressLine1?: string | null; addressLine2?: string | null; city?: string | null; state?: string | null; postalCode?: string | null; createdAt?: string; operationalStatus: string; financialStanding: { status: FinancialStandingStatus; dueToday: boolean; dueDate: string | null }; commercialAccount: { id: string; name: string; billingEmail?: string | null; billingDocument?: string | null } | null; primaryContact: { id?: string; name: string; email: string } | null; plan: { name: string; version?: number; planVersionId?: string; contractedPrice: string; contractedCurrency: string; contractedInterval: string; organizationLimit?: number; userLimit?: number; workOrderLimit?: number } | null; nextBillingDate: string | null; blockDate?: string | null; payment: { condition: string; paidAmount: string; outstandingAmount: string }; commercialAccess: string; effectiveAccess: { allowed: boolean; operationalStatus: string; commercialAccess: string }; lifecycle: string[]; conditions?: Record<string, boolean | string>; trial?: { enabled: boolean; startsAt: string | null; endsAt: string | null }; administrativePending: string[]; users?: OrganizationAdmin[] };
export type OrganizationParams = { page: number; pageSize: number; search?: string; operationalStatus?: string; financialStanding?: FinancialStandingStatus[]; lifecycle?: string[]; commercialAccess?: string[]; sort?: string };
export type OrganizationList = { data: Organization[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };
export const listOrganizations = (params: OrganizationParams) => httpClient.get<OrganizationList>('/platform/organizations', { params }).then((response) => response.data);
export const getOrganization = (id: string) => httpClient.get<Organization>(`/platform/organizations/${id}`).then((response) => response.data);
export type UpdateOrganizationInput = Pick<Organization, 'name' | 'document' | 'phone' | 'email' | 'addressLine1' | 'addressLine2' | 'city' | 'state' | 'postalCode'>;
export const updateOrganization = (id: string, input: UpdateOrganizationInput) => httpClient.patch<Organization>(`/platform/organizations/${id}`, input).then((response) => response.data);
export type OrganizationTransition = 'activate' | 'deactivate' | 'suspend' | 'reactivate';
export const transitionOrganization = (id: string, action: OrganizationTransition, reason?: string) => httpClient.post<Organization>(`/platform/organizations/${id}/${action}`, reason ? { reason } : undefined).then((response) => response.data);
export type ProvisionOrganizationInput = { name: string; document?: string; email?: string; admin: { name: string; email: string }; planVersionId: string; trialEnabled: boolean; trialStartsAt?: string };
export type ProvisionOrganizationResult = { organization: { id: string; name: string; operationalStatus: string }; commercialAccount: { id: string; name: string; billingEmail?: string; billingDocument?: string; primaryContactOrganizationId: string; primaryContactUserId: string }; admin: { id: string; name: string; email: string; role: string; status: string }; subscription: { id: string; planVersionId: string; status: string; trialEnabled: boolean; trialStartsAt: string | null; trialEndsAt: string | null; contractedPrice: string }; activationToken: string };
export const provisionOrganization = (input: ProvisionOrganizationInput) => httpClient.post<ProvisionOrganizationResult>('/platform/organizations', input).then((response) => response.data);
