import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { AuthenticatedPrincipal } from '../auth/authenticated-principal';
import { PrismaService } from '../prisma/prisma.service';
import { CreateExpenseDto, UpdateExpenseDto } from './dto/create-expense.dto';
import { CreateExpensePaymentDto } from './dto/create-expense-payment.dto';
import { ListExpensesDto } from './dto/list-expenses.dto';

const cents = (value: string): bigint => { const [whole, fraction = ''] = value.trim().split('.'); return BigInt(whole) * 100n + BigInt((fraction + '00').slice(0, 2)); };
const money = (value: bigint): string => `${value / 100n}.${(value % 100n).toString().padStart(2, '0')}`;

@Injectable()
export class ExpensesService {
  constructor(private readonly prisma: PrismaService) {}
  private organization(principal: AuthenticatedPrincipal): string { if (principal.role !== 'ADMIN' || !principal.organizationId) throw new ForbiddenException('Organization Admin access required'); return principal.organizationId; }
  private format(expense: any) { const total = cents(expense.amount.toString()); const paid = (expense.payments ?? []).filter((p: any) => p.status === 'CONFIRMED').reduce((sum: bigint, p: any) => sum + cents(p.amount.toString()), 0n); const balance = total - paid; return { ...expense, amount: money(total), dueDate: expense.dueDate instanceof Date ? expense.dueDate.toISOString().slice(0, 10) : expense.dueDate, paid: money(paid), balance: money(balance), financialStatus: paid === 0n ? 'UNPAID' : balance === 0n ? 'PAID' : 'PARTIAL' }; }

  async create(principal: AuthenticatedPrincipal, dto: CreateExpenseDto) { const organizationId = this.organization(principal); return this.format(await this.prisma.expense.create({ data: { organizationId, category: dto.category, description: dto.description.trim(), amount: dto.amount, dueDate: new Date(dto.dueDate) }, include: { payments: true } })); }
  async findOne(principal: AuthenticatedPrincipal, id: string) { const organizationId = this.organization(principal); const expense = await this.prisma.expense.findFirst({ where: { id, organizationId }, include: { payments: { orderBy: { createdAt: 'asc' } } } }); if (!expense) throw new NotFoundException('Expense not found'); return this.format(expense); }

  async list(principal: AuthenticatedPrincipal, query: ListExpensesDto) {
    const organizationId = this.organization(principal); const page = query.page ?? 1; const pageSize = query.pageSize ?? 20;
    const filters = [Prisma.sql`e."organizationId" = ${organizationId}::uuid`];
    const havingFilters = [];
    if (query.id) filters.push(Prisma.sql`e."id" = ${query.id}::uuid`); if (query.status) filters.push(Prisma.sql`e."status" = ${query.status}::"ExpenseStatus"`); if (query.category) filters.push(Prisma.sql`e."category" = ${query.category}::"ExpenseCategory"`); if (query.dueDateFrom) filters.push(Prisma.sql`e."dueDate" >= ${new Date(query.dueDateFrom)}`); if (query.dueDateTo) filters.push(Prisma.sql`e."dueDate" <= ${new Date(query.dueDateTo)}`);
    const confirmed = Prisma.sql`COALESCE(SUM(CASE WHEN p."status" = 'CONFIRMED' THEN p."amount" ELSE 0 END), 0)`;
    if (query.financialStatus === 'UNPAID') havingFilters.push(Prisma.sql`${confirmed} = 0`); if (query.financialStatus === 'PAID') havingFilters.push(Prisma.sql`${confirmed} = e."amount"`); if (query.financialStatus === 'PARTIAL') havingFilters.push(Prisma.sql`${confirmed} > 0 AND ${confirmed} < e."amount"`); if (query.minBalance !== undefined) havingFilters.push(Prisma.sql`e."amount" - ${confirmed} >= ${query.minBalance}::decimal`); if (query.maxBalance !== undefined) havingFilters.push(Prisma.sql`e."amount" - ${confirmed} <= ${query.maxBalance}::decimal`);
    const where = Prisma.join(filters, ' AND ');
    const having = havingFilters.length ? Prisma.sql`HAVING ${Prisma.join(havingFilters, ' AND ')}` : Prisma.empty;
    const rows = await this.prisma.$queryRaw<Array<any>>(Prisma.sql`SELECT e.*, ${confirmed} AS "paid" FROM "Expense" e LEFT JOIN "ExpensePayment" p ON p."expenseId" = e."id" AND p."organizationId" = e."organizationId" WHERE ${where} GROUP BY e."id" ${having} ORDER BY e."dueDate" ASC, e."id" ASC LIMIT ${pageSize} OFFSET ${(page - 1) * pageSize}`);
    const count = await this.prisma.$queryRaw<Array<{ count: bigint }>>(Prisma.sql`SELECT COUNT(*)::bigint AS count FROM (SELECT e."id" FROM "Expense" e LEFT JOIN "ExpensePayment" p ON p."expenseId" = e."id" AND p."organizationId" = e."organizationId" WHERE ${where} GROUP BY e."id" ${having}) counted`);
    const total = Number(count[0]?.count ?? 0); return { data: rows.map((row) => this.format({ ...row, payments: [{ amount: row.paid, status: 'CONFIRMED' }] })), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } };
  }

  private async editable(tx: Prisma.TransactionClient, organizationId: string, id: string) { const expense = await tx.expense.findFirst({ where: { id, organizationId }, include: { payments: { select: { amount: true, status: true } } } }); if (!expense) throw new NotFoundException('Expense not found'); if (expense.status === 'CANCELLED') throw new ConflictException({ code: 'EXPENSE_CANCELLED', detail: 'Cancelled Expenses cannot be edited.' }); if (expense.payments.some((p) => p.status === 'CONFIRMED')) throw new ConflictException({ code: 'EXPENSE_HAS_CONFIRMED_PAYMENTS', detail: 'Expenses with confirmed payments cannot be edited or cancelled.' }); return expense; }
  async update(principal: AuthenticatedPrincipal, id: string, dto: UpdateExpenseDto) { const organizationId = this.organization(principal); const result = await this.prisma.$transaction(async (tx) => { const current = await this.editable(tx, organizationId, id); if (dto.amount !== undefined) { const reserved = current.payments.filter((p) => p.status !== 'CANCELLED').reduce((sum, p) => sum + cents(p.amount.toString()), 0n); if (cents(dto.amount) < reserved) throw new ConflictException({ code: 'EXPENSE_AMOUNT_BELOW_PAYMENTS', detail: 'Expense amount cannot be lower than its existing payments.' }); } return tx.expense.update({ where: { organizationId_id: { organizationId, id } }, data: { ...(dto.category !== undefined && { category: dto.category }), ...(dto.description !== undefined && { description: dto.description.trim() }), ...(dto.amount !== undefined && { amount: dto.amount }), ...(dto.dueDate !== undefined && { dueDate: new Date(dto.dueDate) }) }, include: { payments: true } }); }); return this.format(result); }
  async cancel(principal: AuthenticatedPrincipal, id: string) { const organizationId = this.organization(principal); const result = await this.prisma.$transaction(async (tx) => { await this.editable(tx, organizationId, id); return tx.expense.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CANCELLED' }, include: { payments: true } }); }); return this.format(result); }

  async createPayment(principal: AuthenticatedPrincipal, expenseId: string, dto: CreateExpensePaymentDto) { const organizationId = this.organization(principal); const result = await this.prisma.$transaction(async (tx) => { const locked = await tx.$queryRaw<Array<{ id: string; status: string }>>(Prisma.sql`SELECT "id", "status" FROM "Expense" WHERE "id" = ${expenseId}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`); if (!locked[0]) throw new NotFoundException('Expense not found'); if (locked[0].status === 'CANCELLED') throw new ConflictException({ code: 'EXPENSE_CANCELLED', detail: 'Cancelled Expenses cannot receive payments.' }); const expense = await tx.expense.findFirstOrThrow({ where: { id: expenseId, organizationId }, select: { amount: true } }); const active = await tx.expensePayment.findMany({ where: { expenseId, organizationId, status: { in: ['PENDING', 'CONFIRMED'] } }, select: { amount: true } }); const requested = cents(dto.amount); const reserved = active.reduce((sum, p) => sum + cents(p.amount.toString()), 0n); if (requested > cents(expense.amount.toString()) - reserved) throw new ConflictException({ code: 'EXPENSE_PAYMENT_EXCEEDS_BALANCE', detail: 'Expense payment exceeds the Expense balance.' }); const status = dto.status ?? 'CONFIRMED'; if (status === 'CONFIRMED' && !dto.paidAt) throw new ConflictException({ code: 'EXPENSE_PAYMENT_DATE_REQUIRED', detail: 'Confirmed payments require a payment date.' }); const payment = await tx.expensePayment.create({ data: { organizationId, expenseId, amount: dto.amount, method: dto.method, status, ...(dto.paidAt ? { paidAt: new Date(dto.paidAt) } : {}) } }); return { payment, expense: await tx.expense.findFirstOrThrow({ where: { id: expenseId, organizationId }, include: { payments: true } }) }; }); return { ...this.format(result.expense), payment: result.payment }; }
  async listPayments(principal: AuthenticatedPrincipal, expenseId: string) { const expense = await this.findOne(principal, expenseId); return { data: expense.payments ?? [], financial: { total: expense.amount, paid: expense.paid, balance: expense.balance, status: expense.financialStatus } }; }
  async cancelPayment(principal: AuthenticatedPrincipal, expenseId: string, paymentId: string) { const organizationId = this.organization(principal); const result = await this.prisma.$transaction(async (tx) => { const payment = await tx.expensePayment.findFirst({ where: { id: paymentId, expenseId, organizationId } }); if (!payment) throw new NotFoundException('Expense payment not found'); if (payment.status === 'CANCELLED') throw new ConflictException({ code: 'EXPENSE_PAYMENT_ALREADY_CANCELLED', detail: 'Expense payment is already cancelled.' }); await tx.expensePayment.update({ where: { id: paymentId }, data: { status: 'CANCELLED' } }); return tx.expense.findFirstOrThrow({ where: { id: expenseId, organizationId }, include: { payments: true } }); }); return this.format(result); }
}
