import { useState } from 'react';
import { inputClass } from '@/features/shared/document-components';
import { isValidMoney, normalizeMoney } from '@/features/shared/money';
import type { ExpenseCategory, ExpenseInput } from '../api/payments-api';

const categories: [ExpenseCategory, string][] = [['PARTS_AND_SUPPLIES', 'Peças e insumos'], ['PERSONNEL', 'Pessoal / pró-labore'], ['RENT', 'Aluguel'], ['UTILITIES', 'Água, energia e internet'], ['TAXES', 'Impostos'], ['FINANCIAL_FEES', 'Taxas financeiras'], ['MAINTENANCE', 'Manutenção'], ['MARKETING', 'Marketing'], ['OTHER', 'Outros']];

export function ExpenseForm({ submitting, onSubmit }: { submitting?: boolean; onSubmit: (input: ExpenseInput) => Promise<unknown> }) {
  const [category, setCategory] = useState<ExpenseCategory>('OTHER'); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [dueDate, setDueDate] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!description.trim() || !isValidMoney(amount) || !/[1-9]/.test(amount) || !dueDate) { setError('Informe descrição, valor, e vencimento válidos.'); return; } setError(''); try { await onSubmit({ category, description: description.trim(), amount: normalizeMoney(amount), dueDate }); setDescription(''); setAmount(''); } catch { setError('Não foi possível cadastrar a despesa.'); } }
  return <form onSubmit={submit} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5"><h2 className="font-semibold">Nova despesa</h2>{error && <p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Categoria<select aria-label="Categoria da despesa" className={`${inputClass} mt-2`} value={category} onChange={(e) => setCategory(e.target.value as ExpenseCategory)}>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Descrição<input aria-label="Descrição da despesa" className={`${inputClass} mt-2`} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label className="text-sm font-medium">Valor<input aria-label="Valor da despesa" className={`${inputClass} mt-2`} inputMode="decimal" placeholder="0,00" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="text-sm font-medium">Vencimento<input aria-label="Vencimento da despesa" type="date" className={`${inputClass} mt-2`} value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label></div><button disabled={submitting} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{submitting ? 'Salvando…' : 'Cadastrar despesa'}</button></form>;
}
