import { useState } from 'react';
import { inputClass } from '@/features/shared/document-components';
import type { PaymentInput, PaymentMethod } from '../api/payments-api';
import { normalizeMoney } from '@/features/shared/money';

const methods: [PaymentMethod, string][] = [['CASH', 'Dinheiro'], ['PIX', 'PIX'], ['CREDIT_CARD', 'Cartão de crédito'], ['DEBIT_CARD', 'Cartão de débito'], ['BANK_TRANSFER', 'Transferência bancária'], ['OTHER', 'Outro']];
const decimal = /^(?=.*[1-9])\d+([\.,]\d{1,2})?$/;
const localDateTime = () => { const now = new Date(); const offset = now.getTimezoneOffset() * 60000; return new Date(now.getTime() - offset).toISOString().slice(0, 16); };

export function PaymentForm({ submitting, onSubmit }: { submitting?: boolean; onSubmit: (input: PaymentInput) => Promise<unknown> }) {
  const [amount, setAmount] = useState(''); const [method, setMethod] = useState<PaymentMethod>('PIX'); const [status, setStatus] = useState<'PENDING' | 'CONFIRMED'>('CONFIRMED'); const [paidAt, setPaidAt] = useState(localDateTime); const [error, setError] = useState('');
    async function submit(event: React.FormEvent) { event.preventDefault(); if (!decimal.test(amount)) { setError('Informe um valor decimal válido.'); return; } if (!paidAt) { setError('Informe a data do pagamento.'); return; } setError(''); try { await onSubmit({ amount: normalizeMoney(amount), method, status, paidAt: new Date(paidAt).toISOString() }); setAmount(''); } catch { setError('Não foi possível registrar o pagamento.'); } }
  return <form onSubmit={submit} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5"><h2 className="font-semibold">Registrar pagamento</h2>{error && <p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Valor<input aria-label="Valor" className={`${inputClass} mt-2`} inputMode="decimal" placeholder="0,00" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="text-sm font-medium">Método<select aria-label="Método" className={`${inputClass} mt-2`} value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)}>{methods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Status<select aria-label="Status do pagamento" className={`${inputClass} mt-2`} value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="CONFIRMED">Confirmado</option><option value="PENDING">Pendente</option></select></label><label className="text-sm font-medium">Data do pagamento<input aria-label="Data do pagamento" type="datetime-local" className={`${inputClass} mt-2`} value={paidAt} onChange={(event) => setPaidAt(event.target.value)} /></label></div><button disabled={submitting} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Registrar pagamento</button></form>;
}
