import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Search } from 'lucide-react';
import { formatMoney } from '@/features/shared/money';
import { activateProduct, createProduct, deactivateProduct, getProduct, listProducts, updateProduct, type Product, type ProductInput, type ProductListParams } from '../api/products-api';
import { ProductForm } from '../components/product-form';
const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500';
function paramsFromUrl(s: URLSearchParams): ProductListParams { const active = s.get('active'); return { page: Math.max(1, Number(s.get('page') || 1) || 1), pageSize: Math.min(100, Math.max(1, Number(s.get('pageSize') || 20) || 20)), search: s.get('search') || undefined, active: active === null ? true : active === 'all' ? undefined : active === 'true', lowStock: s.get('lowStock') === 'true' ? true : undefined, sort: (['createdAt', 'name', 'sku', 'salePrice', 'updatedAt'].includes(s.get('sort') || '') ? s.get('sort') : 'createdAt') as ProductListParams['sort'], direction: s.get('direction') === 'desc' ? 'desc' : 'asc' }; }
function writeParams(p: ProductListParams, set: (next: URLSearchParams) => void) { const next = new URLSearchParams(); next.set('page', String(p.page)); next.set('pageSize', String(p.pageSize)); if (p.search) next.set('search', p.search); next.set('active', p.active === undefined ? 'all' : String(p.active)); if (p.lowStock) next.set('lowStock', 'true'); next.set('sort', p.sort); next.set('direction', p.direction); set(next); }
function ErrorState({ retry }: { retry: () => void }) { return <div role="alert">Não foi possível carregar os produtos. <button onClick={retry}>Tentar novamente</button></div>; }
function Shell({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <div className="mx-auto max-w-6xl"><div className="mb-6 flex items-end justify-between"><h1 className="text-2xl font-bold">{title}</h1>{action}</div>{children}</div>; }
export function ProductsListPage() { const [url, setUrl] = useSearchParams(); const params = useMemo(() => paramsFromUrl(url), [url]); const [input, setInput] = useState(params.search ?? ''); const query = useQuery({ queryKey: ['products', params], queryFn: () => listProducts(params) }); useEffect(() => { const t = window.setTimeout(() => { if (input !== (params.search ?? '')) writeParams({ ...params, search: input.trim() || undefined, page: 1 }, setUrl); }, 300); return () => window.clearTimeout(t); }, [input, params, setUrl]); const setParam = (name: keyof ProductListParams, raw: string) => writeParams({ ...params, page: 1, [name]: raw === 'all' ? undefined : raw === 'low' ? true : name === 'active' ? raw === 'true' : raw }, setUrl); const products = query.data?.data ?? []; return <Shell title="Produtos" action={<Link to="/app/products/new"><Plus size={17} />Novo produto</Link>}><div className="rounded-2xl border bg-white p-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="flex-1"><span className="sr-only">Buscar produtos</span><Search size={17} /><input className={inputClass} placeholder="Buscar produtos" value={input} onChange={(e) => setInput(e.target.value)} /></label><select aria-label="Situação" className={inputClass} value={params.active === undefined ? 'all' : String(params.active)} onChange={(e) => setParam('active', e.target.value)}><option value="true">Ativos</option><option value="all">Todos</option><option value="false">Inativos</option></select><select aria-label="Estoque" className={inputClass} value={params.lowStock ? 'low' : 'all'} onChange={(e) => setParam('lowStock', e.target.value)}><option value="all">Todo estoque</option><option value="low">Estoque baixo</option></select></div>{query.isPending ? <div role="status">Carregando produtos…</div> : query.isError ? <ErrorState retry={() => void query.refetch()} /> : <table className="mt-5 w-full text-left text-sm"><thead><tr><th>Nome</th><th>SKU</th><th>Preço</th><th>Estoque</th><th>Situação</th></tr></thead><tbody>{products.map((item) => <tr key={item.id}><td><Link to={`/app/products/${item.id}`}>{item.name}</Link></td><td>{item.sku}</td><td>{formatMoney(item.salePrice)}</td><td className={item.lowStock ? 'font-semibold text-amber-700' : ''}>{item.stockQuantity}{item.lowStock && ' · Estoque baixo'}</td><td>{item.active ? 'Ativo' : 'Inativo'}</td></tr>)}</tbody></table>}</div></Shell>; }
function ProductEditor({ title, initial, onSubmit, submitting, onCancel, omitEmptyOptional }: { title: string; initial?: Partial<ProductInput>; onSubmit: (input: ProductInput) => Promise<unknown>; submitting: boolean; onCancel: () => void; omitEmptyOptional?: boolean }) { return <Shell title={title}><div className="rounded-2xl border bg-white p-5"><ProductForm initial={initial} submitting={submitting} omitEmptyOptional={omitEmptyOptional} onSubmit={onSubmit} onCancel={onCancel} /></div></Shell>; }
export function NewProductPage() { const navigate = useNavigate(); const client = useQueryClient(); const mutation = useMutation({ mutationFn: createProduct, onSuccess: async (saved) => { await client.invalidateQueries({ queryKey: ['products'] }); navigate(`/app/products/${saved.id}`); } }); return <ProductEditor title="Novo produto" submitting={mutation.isPending} onSubmit={(input) => mutation.mutateAsync(input)} onCancel={() => navigate('/app/products')} />; }
export function EditProductPage() { const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const query = useQuery({ queryKey: ['product', id], queryFn: () => getProduct(id) }); const mutation = useMutation({ mutationFn: (input: Partial<ProductInput>) => updateProduct(id, input), onSuccess: async (saved) => { await client.invalidateQueries({ queryKey: ['products'] }); await client.invalidateQueries({ queryKey: ['product', id] }); navigate(`/app/products/${saved.id}`); } }); if (query.isPending) return <div role="status">Carregando produto…</div>; if (query.isError || !query.data) return <ErrorState retry={() => void query.refetch()} />; const current = query.data; const initial = { name: current.name, description: current.description ?? '', sku: current.sku, salePrice: current.salePrice, stockQuantity: current.stockQuantity, stockMinimum: current.stockMinimum }; return <ProductEditor title="Editar produto" initial={initial} omitEmptyOptional={false} submitting={mutation.isPending} onSubmit={(next) => mutation.mutateAsync(Object.fromEntries(Object.entries(next).filter(([field, value]) => value !== initial[field as keyof typeof initial])))} onCancel={() => navigate(`/app/products/${id}`)} />; }
export function ProductDetailPage() { const { id = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: ['product', id], queryFn: () => getProduct(id) }); const action = useMutation({ mutationFn: (active: boolean) => active ? activateProduct(id) : deactivateProduct(id), onSuccess: (saved) => { client.setQueryData(['product', id], saved); void client.invalidateQueries({ queryKey: ['products'] }); } }); if (query.isPending) return <div role="status">Carregando produto…</div>; if (query.isError || !query.data) return <ErrorState retry={() => void query.refetch()} />; const p: Product = query.data; return <div className="mx-auto max-w-4xl"><Link to="/app/products">Voltar para Produtos</Link><div className="my-5 flex items-center justify-between gap-4"><h1 className="text-2xl font-bold">{p.name}</h1><Link to="edit" className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Editar produto</Link></div><section className="grid gap-5 rounded-2xl border bg-white p-6 sm:grid-cols-2"><div>SKU<p>{p.sku}</p></div><div>Preço de venda<p>{formatMoney(p.salePrice)}</p></div><div>Estoque atual<p>{p.stockQuantity}</p></div><div>Estoque mínimo<p>{p.stockMinimum}</p></div><div>Situação<p>{p.lowStock ? 'Estoque baixo' : 'Estoque normal'}</p></div><div>{p.active ? 'Ativo' : 'Inativo'}<button onClick={() => action.mutate(!p.active)}>{p.active ? 'Desativar produto' : 'Ativar produto'}</button></div><div className="sm:col-span-2">Descrição<p>{p.description || 'Nenhuma descrição cadastrada.'}</p></div></section></div>; }
