import { useEffect, useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { listOrganizations, regularizeCommercialSetup, type Organization, type OrganizationParams, type RegularizeCommercialSetupInput } from '../api/organizations-api';
import { PlatformEmpty, PlatformError, PlatformLoading, PlatformStatus } from '../components/platform-primitives';
import { formatPlatformDate, formatPlatformMoney, formatPlatformStatus } from '../platform-formatters';

const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-violet-500';
const labels: Record<string, string> = { ACCESS_ALLOWED: 'Permitido', PAYMENT_GRACE_PERIOD: 'Tolerância', PAYMENT_BLOCKED: 'Bloqueado', PAID_CURRENT: 'Atual', TRIAL: 'Trial', AWAITING_FIRST_PAYMENT: 'Aguardando primeiro pagamento', DELINQUENT: 'Inadimplente', EFFECTIVELY_CANCELLED: 'Cancelada efetiva', PENDING_COMMERCIAL_SETUP: 'Configuração pendente' };
const financialPresentation = { CURRENT: ['Em dia', 'success'], DUE_SOON: ['Vence em breve', 'warning'], OVERDUE: ['Em atraso', 'warning'], PAYMENT_BLOCKED: ['Bloqueada por pagamento', 'danger'] } as const;
const label = (value: string) => labels[value] ?? value;
const tone = (value: string): 'neutral' | 'success' | 'warning' | 'danger' => value === 'ACCESS_ALLOWED' || value === 'ACTIVE' || value === 'PAID_CURRENT' ? 'success' : value === 'PAYMENT_BLOCKED' || value === 'INACTIVE' || value === 'DELINQUENT' || value === 'EFFECTIVELY_CANCELLED' ? 'danger' : 'warning';

function readParams(search: URLSearchParams): OrganizationParams {
  const readArrayParam = (key: string) => search.getAll(key).flatMap((value) => value.split(',')).filter(Boolean);
  const financialStanding = readArrayParam('financialStanding') as NonNullable<OrganizationParams['financialStanding']>;
  return { page: Math.max(1, Number(search.get('page')) || 1), pageSize: Math.min(100, Math.max(1, Number(search.get('pageSize')) || 20)), search: search.get('search') || undefined, operationalStatus: search.get('operationalStatus') || undefined, financialStanding: financialStanding.length ? financialStanding : undefined, lifecycle: readArrayParam('lifecycle'), commercialAccess: readArrayParam('commercialAccess'), sort: search.get('sort') || undefined };
}
function writeParams(params: OrganizationParams, set: (params: URLSearchParams) => void) {
  const next = new URLSearchParams({ page: String(params.page), pageSize: String(params.pageSize) });
  if (params.search) next.set('search', params.search);
  if (params.operationalStatus) next.set('operationalStatus', params.operationalStatus);
  params.financialStanding?.forEach((value) => next.append('financialStanding', value)); params.lifecycle?.forEach((value) => next.append('lifecycle', value)); params.commercialAccess?.forEach((value) => next.append('commercialAccess', value));
  if (params.sort) next.set('sort', params.sort); set(next);
}

export function OrganizationsListPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const params = useMemo(() => readParams(searchParams), [searchParams]); const [input, setInput] = useState(params.search ?? '');
  const [regularizing, setRegularizing] = useState<Organization | null>(null); const [success, setSuccess] = useState('');
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['platform-organizations', params], queryFn: () => listOrganizations(params), placeholderData: (previous) => previous });
  const regularization = useMutation({ mutationFn: ({ id, input }: { id: string; input: RegularizeCommercialSetupInput }) => regularizeCommercialSetup(id, input), onSuccess: async (_, variables) => { const name = regularizing?.name ?? variables.id; setRegularizing(null); setSuccess(`Configuração comercial de ${name} regularizada.`); await queryClient.invalidateQueries({ queryKey: ['platform-organizations'] }); } });
  useEffect(() => setInput(params.search ?? ''), [params.search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (input.trim() !== (params.search ?? '')) writeParams({ ...params, page: 1, search: input.trim() || undefined }, setSearchParams); }, 300); return () => window.clearTimeout(timer); }, [input, params, setSearchParams]);
  const organizations = query.data?.data ?? []; const totalPages = query.data?.meta?.totalPages ?? 0;
  const updateScalarFilter = (key: 'operationalStatus' | 'sort', value: string) => writeParams({ ...params, page: 1, [key]: value || undefined }, setSearchParams);
  const updateArrayFilter = (key: 'financialStanding' | 'lifecycle' | 'commercialAccess', value: string) => writeParams({ ...params, page: 1, [key]: value ? [value] : [] }, setSearchParams);
  const filtered = Boolean(params.search || params.operationalStatus || params.financialStanding?.length || params.lifecycle?.length || params.commercialAccess?.length);
  return <section aria-labelledby="organizations-title" className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-violet-700">Administração da plataforma</p><h2 id="organizations-title" className="mt-2 text-3xl font-bold tracking-tight">Organizations</h2><p className="mt-2 text-slate-600">Oficinas, relação comercial e acesso efetivo.</p></div><Link to="/platform/organizations/new" className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Cadastrar oficina</Link></div>{success && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{success}</p>}{regularizing && <RegularizationForm organization={regularizing} pending={regularization.isPending} apiError={regularization.isError} onCancel={() => { regularization.reset(); setRegularizing(null); }} onSubmit={(form) => regularization.mutate({ id: regularizing.id, input: form })} />}<div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
    <label className="relative block"><span className="sr-only">Buscar Organization</span><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input className={`${inputClass} pl-10`} placeholder="Buscar por Organization, conta ou contato" value={input} onChange={(event) => setInput(event.target.value)} /></label>
    <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select aria-label="Status operacional" className={inputClass} value={params.operationalStatus ?? ''} onChange={(event) => updateScalarFilter('operationalStatus', event.target.value)}><option value="">Todos os status</option><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option><option value="SUSPENDED">Suspenso</option></select><select aria-label="Situação financeira" className={inputClass} value={params.financialStanding?.[0] ?? ''} onChange={(event) => updateArrayFilter('financialStanding', event.target.value)}><option value="">Todas as situações financeiras</option>{Object.entries(financialPresentation).map(([value, [text]]) => <option key={value} value={value}>{text}</option>)}</select><select aria-label="Lifecycle" className={inputClass} value={params.lifecycle?.[0] ?? ''} onChange={(event) => updateArrayFilter('lifecycle', event.target.value)}><option value="">Todos os lifecycles</option>{['TRIAL', 'PAID_CURRENT', 'AWAITING_FIRST_PAYMENT', 'DELINQUENT', 'EFFECTIVELY_CANCELLED', 'PENDING_COMMERCIAL_SETUP'].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select><select aria-label="Acesso comercial" className={inputClass} value={params.commercialAccess?.[0] ?? ''} onChange={(event) => updateArrayFilter('commercialAccess', event.target.value)}><option value="">Todo acesso comercial</option><option value="ACCESS_ALLOWED">Permitido</option><option value="PAYMENT_GRACE_PERIOD">Tolerância</option><option value="PAYMENT_BLOCKED">Bloqueado</option></select><select aria-label="Ordenação" className={inputClass} value={params.sort ?? '-createdAt'} onChange={(event) => updateScalarFilter('sort', event.target.value)}><option value="-createdAt">Mais recentes</option><option value="name">Nome A–Z</option><option value="-name">Nome Z–A</option><option value="operationalStatus">Status</option></select></div>
    {query.isPending && !query.data ? <PlatformLoading label="Carregando Organizations…" /> : query.isError ? <PlatformError error={query.error} onRetry={() => void query.refetch()} /> : organizations.length === 0 ? <div className="mt-4"><PlatformEmpty title={filtered ? 'Nenhuma Organization encontrada' : 'Nenhuma Organization'} description={filtered ? 'Tente ajustar sua busca ou filtros.' : 'As Organizations aparecerão aqui.'} /></div> : <><div className="relative mt-4 overflow-x-auto">{query.isFetching && <span role="status" className="absolute right-2 top-2 text-xs text-slate-400">Atualizando…</span>}<table className="w-full min-w-[1280px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Organization</th><th className="px-3 py-3">Primary Contact</th><th className="px-3 py-3">Plan</th><th className="px-3 py-3">Próxima cobrança</th><th className="px-3 py-3">Resumo de pagamento</th><th className="px-3 py-3">Situação financeira</th><th className="px-3 py-3">Operacional</th><th className="px-3 py-3">Comercial</th><th className="px-3 py-3">Acesso efetivo</th><th className="px-3 py-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{organizations.map((organization) => <OrganizationRow key={organization.id} organization={organization} onRegularize={() => { regularization.reset(); setSuccess(''); setRegularizing(organization); }} />)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 pt-4 text-sm text-slate-500"><span>{query.data?.meta.total ?? 0} Organizations</span><div className="flex items-center gap-2"><button disabled={params.page <= 1} onClick={() => writeParams({ ...params, page: params.page - 1 }, setSearchParams)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span>Página {params.page} de {Math.max(1, totalPages)}</span><button disabled={params.page >= totalPages} onClick={() => writeParams({ ...params, page: params.page + 1 }, setSearchParams)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div></>}</div></section>;
}
function OrganizationRow({ organization: org, onRegularize }: { organization: Organization; onRegularize: () => void }) {
  const [financialLabel, financialTone] = financialPresentation[org.financialStanding.status];
  return <tr><td className="px-3 py-4"><p className="font-semibold">{org.name}</p><p className="text-xs text-slate-500">{org.commercialAccount?.name ?? 'Sem conta comercial'}</p><p className="mt-1 text-xs text-slate-600">Condição: {org.lifecycle.length ? org.lifecycle.map(label).join(', ') : 'Sem condição derivada'}</p>{org.administrativePending.length > 0 && <p className="mt-1 text-xs text-amber-700">Pendência: {org.administrativePending.join(', ')}</p>}</td><td className="px-3 py-4">{org.primaryContact ? <><p>{org.primaryContact.name}</p><p className="text-xs text-slate-500">{org.primaryContact.email}</p></> : <span className="text-amber-700">Não definido</span>}</td><td className="px-3 py-4">{org.plan ? <><p>{org.plan.name}</p><p className="text-xs text-slate-500">{formatPlatformMoney(org.plan.contractedPrice)} / {org.plan.contractedInterval === 'MONTHLY' ? 'mês' : org.plan.contractedInterval}</p></> : '—'}</td><td className="px-3 py-4">{org.nextBillingDate ? formatPlatformDate(org.nextBillingDate) : '—'}</td><td className="px-3 py-4"><p>{org.payment.condition === 'PAID' ? 'Em dia' : org.payment.condition === 'OVERDUE' ? 'Vencido' : 'Em aberto'}</p><p className="text-xs text-slate-500">Pendente: {formatPlatformMoney(org.payment.outstandingAmount)}</p></td><td className="px-3 py-4"><PlatformStatus status={`${financialLabel}${org.financialStanding.dueToday ? ' · vence hoje' : ''}`} tone={financialTone} /></td><td className="px-3 py-4"><PlatformStatus status={formatPlatformStatus(org.operationalStatus)} tone={tone(org.operationalStatus)} /></td><td className="px-3 py-4"><PlatformStatus status={label(org.commercialAccess)} tone={tone(org.commercialAccess)} /></td><td className="px-3 py-4"><PlatformStatus status={org.effectiveAccess.allowed ? 'Permitido' : 'Bloqueado'} tone={org.effectiveAccess.allowed ? 'success' : 'danger'} /></td><td className="px-3 py-4">{org.lifecycle.includes('PENDING_COMMERCIAL_SETUP') ? <button type="button" onClick={onRegularize} className="rounded-lg border border-violet-300 px-3 py-2 text-xs font-semibold text-violet-700">Regularizar <span className="sr-only">{org.name}</span></button> : '—'}</td></tr>;
}

function RegularizationForm({ organization, pending, apiError, onCancel, onSubmit }: { organization: Organization; pending: boolean; apiError: boolean; onCancel: () => void; onSubmit: (input: RegularizeCommercialSetupInput) => void }) {
  const [contractedPrice, setContractedPrice] = useState(''); const [firstDueDate, setFirstDueDate] = useState(''); const [billingDay, setBillingDay] = useState(''); const [validation, setValidation] = useState('');
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const day = Number(billingDay); if (!/^\d+(\.\d{1,2})?$/.test(contractedPrice) || Number(contractedPrice) <= 0) return setValidation('Informe um preço contratado válido.'); if (!firstDueDate) return setValidation('Informe o primeiro vencimento.'); if (!Number.isInteger(day) || day < 1 || day > 28) return setValidation('Informe um dia entre 1 e 28.'); setValidation(''); onSubmit({ contractedPrice, firstDueDate, billingDay: day }); };
  return <form noValidate onSubmit={submit} aria-labelledby="regularization-title" className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 id="regularization-title" className="text-lg font-semibold">Regularizar configuração comercial</h2><p className="mt-1 text-sm text-slate-600">{organization.name}. O primeiro vencimento inicia o ciclo sem criar dívida retroativa.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Preço contratado<input required aria-label="Preço contratado" inputMode="decimal" className={`${inputClass} mt-1`} value={contractedPrice} onChange={(event) => setContractedPrice(event.target.value)} /></label><label className="text-sm font-medium">Primeiro vencimento<input required aria-label="Primeiro vencimento" type="date" className={`${inputClass} mt-1`} value={firstDueDate} onChange={(event) => setFirstDueDate(event.target.value)} /></label><label className="text-sm font-medium">Dia mensal de vencimento<input required aria-label="Dia mensal de vencimento" type="number" min={1} max={28} step={1} className={`${inputClass} mt-1`} value={billingDay} onChange={(event) => setBillingDay(event.target.value)} /></label></div>{(validation || apiError) && <p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{validation || 'Não foi possível regularizar a configuração comercial.'}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" disabled={pending} onClick={onCancel} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Cancelar</button><button type="submit" disabled={pending} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Regularizando…' : 'Confirmar regularização'}</button></div></form>;
}
