import { ArrowLeft, Search } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useMemo, useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getPlan, listPlans, type Plan, type PlanParams, type PlanVersion } from '../api/plans-api';
import { PlatformEmpty, PlatformError, PlatformLoading, PlatformSection, PlatformStatus } from '../components/platform-primitives';
import { formatPlatformDate, formatPlatformMoney } from '../platform-formatters';

const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-violet-500';
const versionStatus = (plan: Plan, version: PlanVersion) => plan.archivedAt ? ['Arquivada', 'neutral'] as const : version.status === 'PUBLISHED' ? ['Publicada', 'success'] as const : ['Rascunho', 'warning'] as const;
const intervalLabel: Record<string, string> = { MONTHLY: 'mês' };

function readParams(search: URLSearchParams): PlanParams { return { page: Math.max(1, Number(search.get('page')) || 1), pageSize: Math.min(100, Math.max(1, Number(search.get('pageSize')) || 20)), search: search.get('search') || undefined }; }
function writeParams(params: PlanParams, set: (next: URLSearchParams) => void) { const next = new URLSearchParams({ page: String(params.page), pageSize: String(params.pageSize) }); if (params.search) next.set('search', params.search); set(next); }
function price(version: PlanVersion) { return version.currency === 'BRL' ? formatPlatformMoney(version.price) : `${version.price} ${version.currency}`; }
function limit(value: number | null) { return value === null ? 'Ilimitado' : String(value); }

export function PlansListPage() {
  const [url, setUrl] = useSearchParams(); const params = useMemo(() => readParams(url), [url]); const [input, setInput] = useState(params.search ?? '');
  const query = useQuery({ queryKey: ['platform-plans', params], queryFn: () => listPlans(params), placeholderData: (previous) => previous });
  useEffect(() => setInput(params.search ?? ''), [params.search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (input.trim() !== (params.search ?? '')) writeParams({ ...params, page: 1, search: input.trim() || undefined }, setUrl); }, 300); return () => window.clearTimeout(timer); }, [input, params, setUrl]);
  const plans = query.data?.data ?? []; const totalPages = query.data?.meta.totalPages ?? 0; const hasSearch = Boolean(params.search);
  return <section aria-labelledby="plans-title" className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-violet-700">Administração da plataforma</p><h2 id="plans-title" className="mt-2 text-3xl font-bold tracking-tight">Plans</h2><p className="mt-2 text-slate-600">Ofertas comerciais e suas Plan Versions.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="relative block"><span className="sr-only">Buscar Plan</span><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input className={`${inputClass} pl-10`} placeholder="Buscar Plan" value={input} onChange={(event) => setInput(event.target.value)} /></label>{query.isPending && !query.data ? <div className="mt-4"><PlatformLoading label="Carregando Plans…" /></div> : query.isError ? <div className="mt-4"><PlatformError error={query.error} fallback="Não foi possível carregar os Plans." onRetry={() => void query.refetch()} /></div> : plans.length === 0 ? <div className="mt-4"><PlatformEmpty title={hasSearch ? 'Nenhum Plan encontrado' : 'Nenhum Plan'} description={hasSearch ? 'Tente ajustar sua busca.' : 'Os Plans aparecerão aqui.'} /></div> : <><div className="relative mt-4 overflow-x-auto">{query.isFetching && <span role="status" className="absolute right-2 top-2 text-xs text-slate-400">Atualizando…</span>}<table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Plan</th><th className="px-3 py-3">Estado</th><th className="px-3 py-3">Plan Versions</th><th className="px-3 py-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{plans.map((plan) => <PlanRow key={plan.id} plan={plan} />)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 pt-4 text-sm text-slate-500"><span>{query.data?.meta.total ?? 0} Plans</span><div className="flex items-center gap-2"><button disabled={params.page <= 1} onClick={() => writeParams({ ...params, page: params.page - 1 }, setUrl)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span>Página {params.page} de {Math.max(1, totalPages)}</span><button disabled={params.page >= totalPages} onClick={() => writeParams({ ...params, page: params.page + 1 }, setUrl)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div></>}</div></section>;
}

function PlanRow({ plan }: { plan: Plan }) { return <tr><td className="px-3 py-4"><p className="font-semibold">{plan.name}</p><p className="text-xs text-slate-500">{plan.id}</p></td><td className="px-3 py-4"><PlatformStatus status={plan.archivedAt ? 'Arquivado' : 'Ativo'} tone={plan.archivedAt ? 'neutral' : 'success'} /></td><td className="px-3 py-4">{plan.versions.length === 0 ? <span className="text-slate-500">Nenhuma Plan Version</span> : <div className="space-y-2">{plan.versions.map((version) => { const [label, tone] = versionStatus(plan, version); return <div key={version.id} className="flex flex-wrap items-center gap-2"><span>v{version.version}</span><PlatformStatus status={label} tone={tone} /><span className="text-xs text-slate-500">{price(version)} / {intervalLabel[version.interval] ?? version.interval}</span></div>; })}</div>}</td><td className="px-3 py-4"><Link className="font-semibold text-violet-700 hover:underline" to={`/platform/plans/${plan.id}`}>Visualizar</Link></td></tr>; }

export function PlanDetailPage() { const { id = '' } = useParams(); const query = useQuery({ queryKey: ['platform-plan', id], queryFn: () => getPlan(id), enabled: Boolean(id) }); if (query.isPending) return <PlatformLoading label="Carregando Plan…" />; if (query.isError || !query.data) return <PlatformError error={query.error} fallback="Não foi possível carregar o Plan." onRetry={() => void query.refetch()} />; const plan = query.data; return <section className="space-y-6"><Link to="/platform/plans" className="inline-flex items-center gap-2 text-sm font-semibold text-violet-700"><ArrowLeft size={16} />Voltar para Plans</Link><div><h2 className="text-3xl font-bold tracking-tight">{plan.name}</h2><p className="mt-2 text-slate-600">Plan {plan.id}</p></div><PlatformSection title="Plan Versions">{plan.versions.length === 0 ? <PlatformEmpty title="Nenhuma Plan Version" description="Este Plan ainda não possui versões cadastradas." /> : <div className="space-y-5">{plan.versions.map((version) => <VersionDetails key={version.id} plan={plan} version={version} />)}</div>}</PlatformSection></section>; }

function VersionDetails({ plan, version }: { plan: Plan; version: PlanVersion }) { const [label, tone] = versionStatus(plan, version); return <article className="rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Plan Version v{version.version}</h3><PlatformStatus status={label} tone={tone} /></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><DetailField label="Preço" value={price(version)} /><DetailField label="Moeda" value={version.currency} /><DetailField label="Intervalo" value={intervalLabel[version.interval] ?? version.interval} /><DetailField label="Limite de Organizations" value={limit(version.organizationLimit)} /><DetailField label="Limite de Users" value={limit(version.userLimit)} /><DetailField label="Limite de Work Orders" value={limit(version.workOrderLimit)} /><DetailField label="Período de carência" value={`${version.gracePeriodDays} dias`} /><DetailField label="Publicada em" value={version.publishedAt ? formatPlatformDate(version.publishedAt) : 'Não publicada'} /></dl></article>; }
function DetailField({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value}</dd></div>; }
