import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, ChevronUp, Plus, Search } from 'lucide-react';
import { ApiError } from '@/shared/api/http';
import { createService, getService, listServices, serviceAction, updateService, type Service, type ServiceInput, type ServiceListParams } from '../api/services-api';
import { ServiceForm } from '../components/service-form';
import { formatMoney } from '@/features/shared/money';

const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none ring-blue-500 placeholder:text-slate-400 focus:ring-2';
const sorts = ['createdAt', 'name', 'price', 'updatedAt'] as const;
const date = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' }).format(parsed); };
const money = formatMoney;
function paramsFromUrl(search: URLSearchParams): ServiceListParams { const active = search.get('active'); return { page: Math.max(1, Number(search.get('page') ?? 1) || 1), pageSize: Math.min(100, Math.max(1, Number(search.get('pageSize') ?? 20) || 20)), search: search.get('search') || undefined, active: active === null ? true : active === 'all' ? undefined : active === 'true', sort: (sorts.includes(search.get('sort') as typeof sorts[number]) ? search.get('sort') : 'createdAt') as ServiceListParams['sort'], direction: search.get('direction') === 'desc' ? 'desc' : 'asc' }; }
function writeParams(params: ServiceListParams, set: (next: URLSearchParams) => void) { const next = new URLSearchParams(); next.set('page', String(params.page)); next.set('pageSize', String(params.pageSize)); if (params.search) next.set('search', params.search); next.set('active', params.active === undefined ? 'all' : String(params.active)); next.set('sort', params.sort); next.set('direction', params.direction); set(next); }

export function ServicesListPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const params = useMemo(() => paramsFromUrl(searchParams), [searchParams]); const [searchInput, setSearchInput] = useState(params.search ?? ''); const client = useQueryClient();
  const query = useQuery({ queryKey: ['services', params], queryFn: () => listServices(params), placeholderData: (previous) => previous });
  const toggle = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => serviceAction(id, active ? 'deactivate' : 'activate'), onSuccess: () => void client.invalidateQueries({ queryKey: ['services'] }) });
  useEffect(() => { setSearchInput(params.search ?? ''); }, [params.search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (searchInput !== (params.search ?? '')) writeParams({ ...params, search: searchInput.trim() || undefined, page: 1 }, setSearchParams); }, 300); return () => window.clearTimeout(timer); }, [searchInput, params, setSearchParams]);
  function setParam(name: keyof ServiceListParams, value: string) { writeParams({ ...params, page: name === 'page' ? Number(value) : 1, [name]: value === 'all' ? undefined : name === 'active' ? value === 'true' : value }, setSearchParams); }
  const rows = query.data?.data ?? []; const totalPages = query.data?.meta.totalPages ?? 0;
  return <><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold tracking-tight">Serviços</h2><p className="mt-1 text-sm text-slate-500">Gerencie o catálogo de trabalho da sua oficina.</p></div><Link to="new" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} />Novo serviço</Link></div>
    <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Buscar por nome ou descrição</span><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input className={`${inputClass} pl-10`} placeholder="Buscar por nome ou descrição" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} /></label><select aria-label="Situação" className={`${inputClass} lg:w-44`} value={params.active === undefined ? 'all' : String(params.active)} onChange={(event) => setParam('active', event.target.value)}><option value="true">Ativos</option><option value="all">Todos</option><option value="false">Inativos</option></select><select aria-label="Ordenar por" className={`${inputClass} lg:w-44`} value={params.sort} onChange={(event) => setParam('sort', event.target.value)}><option value="createdAt">Cadastro</option><option value="name">Nome</option><option value="price">Preço</option><option value="updatedAt">Atualização</option></select><button type="button" aria-label="Alternar direção" onClick={() => setParam('direction', params.direction === 'asc' ? 'desc' : 'asc')} className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-3 text-slate-600">{params.direction === 'asc' ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button></div>
      {query.isPending && !query.data ? <div role="status" className="py-8">Carregando serviços…</div> : query.isError ? <div role="alert" className="py-8 text-center text-red-700">Não foi possível carregar os serviços.<button className="ml-2 underline" onClick={() => void query.refetch()}>Tentar novamente</button></div> : rows.length === 0 ? <div className="py-16 text-center"><p className="font-semibold">Nenhum serviço encontrado</p><p className="mt-1 text-sm text-slate-500">Ajuste sua busca ou cadastre um novo serviço.</p></div> : <><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Nome</th><th className="px-3 py-3">Descrição</th><th className="px-3 py-3">Preço</th><th className="px-3 py-3">Situação</th><th className="px-3 py-3">Cadastro</th><th className="px-3 py-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((item) => <ServiceRow key={item.id} service={item} onToggle={() => toggle.mutate({ id: item.id, active: item.active })} />)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 pt-4 text-sm text-slate-500"><span>{query.data?.meta.total ?? 0} serviço(s)</span><div className="flex items-center gap-2"><button disabled={params.page <= 1} onClick={() => setParam('page', String(params.page - 1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span>Página {params.page} de {Math.max(1, totalPages)}</span><button disabled={params.page >= totalPages} onClick={() => setParam('page', String(params.page + 1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div></>}</section></>;
}

function ServiceRow({ service, onToggle }: { service: Service; onToggle: () => void }) { return <tr><td className="px-3 py-4 font-medium"><Link to={service.id} className="text-blue-700 hover:underline">{service.name}</Link></td><td className="max-w-xs truncate px-3 py-4 text-slate-600">{service.description || '—'}</td><td className="px-3 py-4 font-semibold">{money(service.price)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${service.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{service.active ? 'Ativo' : 'Inativo'}</span></td><td className="px-3 py-4">{date(service.createdAt)}</td><td className="space-x-3 px-3 py-4"><Link to={`${service.id}/edit`} className="font-semibold text-blue-700">Editar</Link><button onClick={onToggle} className="font-semibold text-slate-600" aria-label={`${service.active ? 'Desativar' : 'Ativar'} serviço`}>{service.active ? 'Desativar' : 'Ativar'}</button></td></tr>; }

export function NewServicePage() { const navigate = useNavigate(); const client = useQueryClient(); const mutation = useMutation({ mutationFn: createService, onSuccess: async (item) => { await client.invalidateQueries({ queryKey: ['services'] }); navigate(`/app/services/${item.id}`); } }); return <ServiceEditor title="Novo serviço" description="Cadastre um item de trabalho para reutilizar em documentos." submitting={mutation.isPending} onSubmit={(value) => mutation.mutateAsync(value)} onCancel={() => navigate('/app/services')} />; }
export function EditServicePage() { const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const query = useQuery({ queryKey: ['service', id], queryFn: () => getService(id) }); const mutation = useMutation({ mutationFn: (value: Partial<ServiceInput>) => updateService(id, value), onSuccess: async (saved) => { await client.invalidateQueries({ queryKey: ['services'] }); await client.invalidateQueries({ queryKey: ['service', id] }); navigate(`/app/services/${saved.id}`); } }); if (query.isPending) return <div role="status">Carregando serviço…</div>; if (query.isError || !query.data) return <div role="alert">Não foi possível carregar o serviço.</div>; const current = query.data; const initial: Partial<ServiceInput> = { name: current.name, description: current.description ?? '', price: current.price }; return <ServiceEditor title="Editar serviço" description="Atualize os dados do serviço." initial={initial} omitEmptyOptional={false} submitting={mutation.isPending} onSubmit={(value) => { const changed = Object.fromEntries(Object.entries(value).filter(([field, next]) => next !== (initial[field as keyof typeof initial] ?? ''))) as Partial<ServiceInput>; return mutation.mutateAsync(changed); }} onCancel={() => navigate(`/app/services/${id}`)} />; }

export function ServiceDetailPage() { const { id = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: ['service', id], queryFn: () => getService(id) }); const action = useMutation({ mutationFn: (active: boolean) => serviceAction(id, active ? 'deactivate' : 'activate'), onSuccess: (saved) => { client.setQueryData(['service', id], saved); void client.invalidateQueries({ queryKey: ['services'] }); } }); if (query.isPending) return <div role="status">Carregando serviço…</div>; if (query.isError || !query.data) return <div role="alert">Não foi possível carregar o serviço.</div>; const service = query.data; return <div className="mx-auto max-w-3xl"><Link to="/app/services" className="text-sm font-semibold text-blue-700">← Voltar para Serviços</Link><div className="mb-6 mt-5 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">{service.name}</h1><p className="mt-1 text-sm text-slate-500">Detalhes do serviço</p></div><div className="flex gap-2"><Link to="edit" className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Editar</Link><button onClick={() => action.mutate(service.active)} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{service.active ? 'Desativar serviço' : 'Ativar serviço'}</button></div></div><section className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-slate-500">Nome</p><p className="mt-1">{service.name}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Preço</p><p className="mt-1">{money(service.price)}</p></div><div className="sm:col-span-2"><p className="text-xs font-semibold uppercase text-slate-500">Descrição</p><p className="mt-1 whitespace-pre-wrap">{service.description || 'Nenhuma descrição cadastrada.'}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Situação</p><p className="mt-1">{service.active ? 'Ativo' : 'Inativo'}</p></div></section></div>; }
function ServiceEditor({ title, description, initial, submitting, omitEmptyOptional, onSubmit, onCancel }: { title: string; description: string; initial?: Partial<ServiceInput>; submitting: boolean; omitEmptyOptional?: boolean; onSubmit: (value: ServiceInput) => Promise<unknown>; onCancel: () => void }) { return <div className="mx-auto max-w-3xl"><Link to="/app/services" className="mb-5 inline-flex text-sm font-semibold text-blue-700">← Voltar para Serviços</Link><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><ServiceForm initial={initial} submitting={submitting} omitEmptyOptional={omitEmptyOptional} onSubmit={onSubmit} onCancel={onCancel} /></div></div>; }
