import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { inputClass } from '@/features/shared/document-components';
import { activateSupplier, createSupplier, deactivateSupplier, getSupplier, listSuppliers, updateSupplier, type SupplierInput } from '../api/suppliers-api';

function SupplierForm({ initial, submitting, onSubmit }: { initial?: Partial<SupplierInput>; submitting?: boolean; onSubmit: (input: SupplierInput) => Promise<unknown> }) {
  const [name, setName] = useState(initial?.name ?? ''); const [document, setDocument] = useState(initial?.document ?? ''); const [email, setEmail] = useState(initial?.email ?? ''); const [phone, setPhone] = useState(initial?.phone ?? ''); const [notes, setNotes] = useState(initial?.notes ?? ''); const [error, setError] = useState('');
  useEffect(() => { setName(initial?.name ?? ''); setDocument(initial?.document ?? ''); setEmail(initial?.email ?? ''); setPhone(initial?.phone ?? ''); setNotes(initial?.notes ?? ''); }, [initial]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) { setError('Informe o nome do fornecedor.'); return; } setError(''); try { await onSubmit({ name: name.trim(), ...(document.trim() ? { document: document.trim() } : {}), ...(email.trim() ? { email: email.trim() } : {}), ...(phone.trim() ? { phone: phone.trim() } : {}), ...(notes.trim() ? { notes: notes.trim() } : {}) }); } catch { setError('Não foi possível salvar o fornecedor.'); } }
  return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Dados do fornecedor</h2>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nome<input aria-label="Nome do fornecedor" className={`${inputClass} mt-2`} value={name} onChange={(e) => setName(e.target.value)} /></label><label className="text-sm font-medium">CPF/CNPJ<input aria-label="CPF/CNPJ do fornecedor" className={`${inputClass} mt-2`} value={document} onChange={(e) => setDocument(e.target.value)} /></label><label className="text-sm font-medium">E-mail<input aria-label="E-mail do fornecedor" type="email" className={`${inputClass} mt-2`} value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="text-sm font-medium">Telefone<input aria-label="Telefone do fornecedor" className={`${inputClass} mt-2`} value={phone} onChange={(e) => setPhone(e.target.value)} /></label><label className="text-sm font-medium sm:col-span-2">Observações<textarea aria-label="Observações do fornecedor" className={`${inputClass} mt-2 min-h-24`} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div><button disabled={submitting} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{submitting ? 'Salvando…' : 'Salvar fornecedor'}</button></form>;
}

export function SuppliersListPage() { const [params, setParams] = useSearchParams(); const query = useQuery({ queryKey: ['suppliers', params.toString()], queryFn: () => listSuppliers({ page: 1, pageSize: 100, search: params.get('search') || undefined, active: params.get('active') === 'all' ? undefined : params.get('active') !== 'false' }) }); const [search, setSearch] = useState(params.get('search') ?? ''); const client = useQueryClient(); const create = useMutation({ mutationFn: createSupplier, onSuccess: async (supplier) => { await client.invalidateQueries({ queryKey: ['suppliers'] }); window.location.assign(`/app/suppliers/${supplier.id}`); } }); return <div className="mx-auto max-w-6xl"><div className="mb-6 flex items-end justify-between"><div><h1 className="text-2xl font-bold">Fornecedores</h1><p className="mt-1 text-sm text-slate-500">Gerencie parceiros e origens de Products.</p></div><Link to="new" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">+ Novo fornecedor</Link></div><section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><input aria-label="Buscar fornecedores" className={inputClass} placeholder="Buscar fornecedores" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { const next = new URLSearchParams(params); if (search.trim()) next.set('search', search.trim()); else next.delete('search'); setParams(next); } }} /><select aria-label="Situação do fornecedor" className={`${inputClass} max-w-xs`} value={params.get('active') ?? 'true'} onChange={(e) => { const next = new URLSearchParams(params); next.set('active', e.target.value); setParams(next); }}><option value="true">Ativos</option><option value="all">Todos</option><option value="false">Inativos</option></select></div>{query.isPending ? <div role="status">Carregando fornecedores…</div> : query.isError ? <div role="alert">Não foi possível carregar os fornecedores.</div> : query.data.data.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">Nenhum fornecedor encontrado.</p> : <table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="px-2 py-3">Nome</th><th className="px-2 py-3">CPF/CNPJ</th><th className="px-2 py-3">Contato</th><th className="px-2 py-3">Situação</th></tr></thead><tbody className="divide-y">{query.data.data.map((supplier) => <tr key={supplier.id}><td className="px-2 py-4 font-semibold"><Link to={supplier.id} className="text-blue-700">{supplier.name}</Link></td><td className="px-2 py-4">{supplier.document ?? '—'}</td><td className="px-2 py-4">{supplier.phone ?? supplier.email ?? '—'}</td><td className="px-2 py-4">{supplier.active ? 'Ativo' : 'Inativo'}</td></tr>)}</tbody></table>}</section><div className="mt-5"><SupplierForm submitting={create.isPending} onSubmit={(input) => create.mutateAsync(input)} /></div></div>; }
export function NewSupplierPage() { const navigate = useNavigate(); const create = useMutation({ mutationFn: createSupplier, onSuccess: (supplier) => navigate(`/app/suppliers/${supplier.id}`) }); return <div className="mx-auto max-w-3xl"><Link to="/app/suppliers" className="mb-5 inline-flex text-sm font-semibold text-blue-700">← Voltar para Fornecedores</Link><h1 className="mb-5 text-2xl font-bold">Novo fornecedor</h1><SupplierForm submitting={create.isPending} onSubmit={(input) => create.mutateAsync(input)} /></div>; }
export function SupplierDetailPage() { const { id = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: ['supplier', id], queryFn: () => getSupplier(id) }); const update = useMutation({ mutationFn: (input: Partial<SupplierInput>) => updateSupplier(id, input), onSuccess: (supplier) => client.setQueryData(['supplier', id], supplier) }); const toggle = useMutation({ mutationFn: (active: boolean) => active ? activateSupplier(id) : deactivateSupplier(id), onSuccess: (supplier) => { client.setQueryData(['supplier', id], supplier); void client.invalidateQueries({ queryKey: ['suppliers'] }); } }); if (query.isPending) return <div role="status">Carregando fornecedor…</div>; if (query.isError || !query.data) return <div role="alert">Fornecedor não encontrado.</div>; const supplier = query.data; const initial: Partial<SupplierInput> = { name: supplier.name, document: supplier.document ?? undefined, email: supplier.email ?? undefined, phone: supplier.phone ?? undefined, notes: supplier.notes ?? undefined }; return <div className="mx-auto max-w-3xl"><Link to="/app/suppliers" className="mb-5 inline-flex text-sm font-semibold text-blue-700">← Voltar para Fornecedores</Link><div className="mb-5 flex items-end justify-between"><div><h1 className="text-2xl font-bold">{supplier.name}</h1><p className="mt-1 text-sm text-slate-500">{supplier.active ? 'Ativo' : 'Inativo'}</p></div><button onClick={() => toggle.mutate(!supplier.active)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">{supplier.active ? 'Desativar' : 'Ativar'}</button></div><SupplierForm initial={initial} submitting={update.isPending} onSubmit={(input) => update.mutateAsync(input)} /></div>; }
