import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { listCustomers, type Customer } from '@/features/customers/api/customers-api';
import { listVehicles, type Vehicle } from '@/features/vehicles/api/vehicles-api';
import { BackLink, CustomerVehicleFields, getStatusLabel, inputClass, ItemEditor, ItemsTable, money, Pager, quoteStatusLabels, Status } from '@/features/shared/document-components';
import { addQuoteItem, createQuote, getQuote, listQuotes, quoteAction, removeQuoteItem, updateQuoteItem } from '../api/quotes-api';
import { convertQuote } from '@/features/work-orders/api/work-orders-api';
import { ApiError, getUserFacingError } from '@/shared/api/http';

const statuses = ['DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'];
type QuoteListParams = { page: number; pageSize: number; search?: string; status?: string };
function quoteParams(search: URLSearchParams): QuoteListParams { const page = Number(search.get('page')); return { page: Number.isInteger(page) && page > 0 ? page : 1, pageSize: 10, search: search.get('search') || undefined, status: search.get('status') || undefined }; }
function writeQuoteParams(params: QuoteListParams, set: (next: URLSearchParams) => void) { const next = new URLSearchParams(); if (params.page > 1) next.set('page', String(params.page)); if (params.search) next.set('search', params.search); if (params.status) next.set('status', params.status); set(next); }
function Options() { const customers = useQuery({ queryKey: ['customers', 'document-options'], queryFn: () => listCustomers({ page: 1, pageSize: 100, active: true, sort: 'name', direction: 'asc' }) }); const vehicles = useQuery({ queryKey: ['vehicles', 'document-options'], queryFn: () => listVehicles({ page: 1, pageSize: 100, active: true, sort: 'plate', direction: 'asc' }) }); return { customers: customers.data?.data ?? [], vehicles: vehicles.data?.data ?? [], loading: customers.isPending || vehicles.isPending, error: customers.isError || vehicles.isError }; }
export function QuotesListPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const params = useMemo(() => quoteParams(searchParams), [searchParams]);
  const [searchInput, setSearchInput] = useState(params.search ?? '');
  const query = useQuery({ queryKey: ['quotes', params], queryFn: () => listQuotes(params), placeholderData: (previous) => previous });
  const rows = query.data?.data ?? [];
  const customers = useQuery({ queryKey: ['customers', 'quote-list'], queryFn: () => listCustomers({ page: 1, pageSize: 100, active: true, sort: 'name', direction: 'asc' }), enabled: rows.length > 0 });
  const vehicles = useQuery({ queryKey: ['vehicles', 'quote-list'], queryFn: () => listVehicles({ page: 1, pageSize: 100, active: true, sort: 'plate', direction: 'asc' }), enabled: rows.length > 0 });
  const customerById = useMemo(() => new Map((customers.data?.data ?? []).map((customer: Customer) => [customer.id, customer])), [customers.data]);
  const vehicleById = useMemo(() => new Map((vehicles.data?.data ?? []).map((vehicle: Vehicle) => [vehicle.id, vehicle])), [vehicles.data]);
  useEffect(() => { setSearchInput(params.search ?? ''); }, [params.search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (searchInput.trim() !== (params.search ?? '')) writeQuoteParams({ ...params, search: searchInput.trim() || undefined, page: 1 }, setSearchParams); }, 300); return () => window.clearTimeout(timer); }, [searchInput, params, setSearchParams]);
  function setParam(name: 'page' | 'status', value: string) { writeQuoteParams({ ...params, page: name === 'page' ? Number(value) : 1, status: name === 'status' ? value || undefined : params.status }, setSearchParams); }
  const pager = query.data && query.data.meta.totalPages > 1 ? <Pager page={params.page} totalPages={query.data.meta.totalPages} onPage={(page) => setParam('page', String(page))} /> : null;
  return <><div className="mb-6 flex items-start justify-between"><div><h1 className="text-2xl font-bold">Orçamentos</h1><p className="mt-1 text-sm text-slate-500">Acompanhe propostas e aprovações.</p></div><Link to="new" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">+ Novo orçamento</Link></div><section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Buscar por número, cliente ou placa</span><input aria-label="Buscar por número, cliente ou placa" className={inputClass} placeholder="Buscar por número, cliente ou placa" value={searchInput} onChange={(e) => setSearchInput(e.target.value)} /></label><select aria-label="Filtrar por status" className={`${inputClass} sm:max-w-xs`} value={params.status ?? ''} onChange={(e) => setParam('status', e.target.value)}><option value="">Todos os status</option>{statuses.map((s) => <option key={s} value={s}>{quoteStatusLabels[s]}</option>)}</select></div>{query.isPending && !query.data ? <div role="status">Carregando orçamentos…</div> : query.isError ? <div role="alert">Não foi possível carregar os orçamentos.</div> : rows.length === 0 ? <><p className="py-12 text-center text-slate-500">Nenhum orçamento encontrado.</p>{pager}</> : <><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="px-2 py-3">Número</th><th className="px-2 py-3">Cliente</th><th className="px-2 py-3">Veículo/placa</th><th className="px-2 py-3">Status</th><th className="px-2 py-3">Itens</th><th className="px-2 py-3">Total</th><th /></tr></thead><tbody className="divide-y">{rows.map((q) => { const customer = customerById.get(q.customerId); const vehicle = vehicleById.get(q.vehicleId); return <tr key={q.id}><td className="px-2 py-4 font-semibold">#{q.number}</td><td className="px-2 py-4">{customer?.name ?? q.customer?.name ?? q.customerId}</td><td className="px-2 py-4">{vehicle ? `${vehicle.brand} ${vehicle.model} — ${vehicle.plate}` : q.vehicle ? `${q.vehicle.brand} ${q.vehicle.model} — ${q.vehicle.plate}` : q.vehicleId}</td><td className="px-2 py-4"><Status value={q.status} /></td><td className="px-2 py-4">{q.items.length ? q.items.map((item) => <div key={item.id}>{item.description} ({item.quantity.replace(/\.000$/, '')})</div>) : 'Nenhum item'}</td><td className="px-2 py-4 font-semibold">{money(q.total)}</td><td className="px-2 py-4 text-right"><Link className="font-semibold text-blue-700" to={q.id}>Visualizar</Link></td></tr>; })}</tbody></table></div>{pager}</>}</section></>;
}
export function NewQuotePage() { const navigate = useNavigate(); const client = useQueryClient(); const { customers, vehicles, loading, error } = Options(); const [customerId, setCustomer] = useState(''); const [vehicleId, setVehicle] = useState(''); const [notes, setNotes] = useState(''); const [message, setMessage] = useState(''); const mutation = useMutation({ mutationFn: () => createQuote({ customerId, vehicleId, ...(notes.trim() ? { notes: notes.trim() } : {}) }), onSuccess: async (q) => { await Promise.all([client.invalidateQueries({ queryKey: ['quotes'] }), client.invalidateQueries({ queryKey: ['dashboard'] })]); navigate(`/app/quotes/${q.id}`); } }); if (loading) return <div role="status">Carregando opções…</div>; if (error) return <div role="alert">Não foi possível carregar clientes e veículos.</div>; const mutationMessage = mutation.error instanceof ApiError ? getUserFacingError(mutation.error.problem, 'Não foi possível criar o orçamento.') : 'Não foi possível criar o orçamento.'; return <div className="mx-auto max-w-3xl"><BackLink to="/app/quotes">Voltar para Orçamentos</BackLink><h1 className="text-2xl font-bold">Novo orçamento</h1><p className="mt-1 text-sm text-slate-500">Crie uma proposta para um cliente e veículo.</p><form onSubmit={(e) => { e.preventDefault(); if (!customerId || !vehicleId) { setMessage('Selecione cliente e veículo.'); return; } setMessage(''); mutation.mutate(); }} className="mt-6 space-y-6 rounded-2xl border bg-white p-6 shadow-sm"><CustomerVehicleFields {...{ customers, vehicles, customerId, vehicleId, setCustomer, setVehicle }} /><label className="text-sm font-medium text-slate-700">Observações<textarea className={`${inputClass} mt-2 min-h-28`} value={notes} onChange={(e) => setNotes(e.target.value)} /></label>{(message || mutation.isError) && <p role="alert" className="text-sm text-red-600">{message || mutationMessage}</p>}<div className="flex justify-end gap-3"><Link to="/app/quotes" className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancelar</Link><button disabled={mutation.isPending} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{mutation.isPending ? 'Salvando…' : 'Salvar orçamento'}</button></div></form></div>; }
export function QuoteDetailPage() {
  const { id = '' } = useParams();
  const navigate = useNavigate();
  const client = useQueryClient();
  const query = useQuery({ queryKey: ['quote', id], queryFn: () => getQuote(id) });
  const [feedback, setFeedback] = useState('');
  const refreshAfterChange = async (saved: Awaited<ReturnType<typeof quoteAction>>) => {
    client.setQueryData(['quote', id], saved);
    await Promise.all([
      client.invalidateQueries({ queryKey: ['quote', id] }),
      client.invalidateQueries({ queryKey: ['quotes'] }),
      client.invalidateQueries({ queryKey: ['dashboard'] }),
    ]);
  };
  const action = useMutation({ mutationFn: (name: 'submit' | 'approve' | 'reject' | 'cancel') => quoteAction(id, name), onSuccess: async (saved) => { setFeedback(`Orçamento atualizado para ${getStatusLabel(saved.status)}.`); await refreshAfterChange(saved); }, onError: () => setFeedback('Não foi possível alterar o status do orçamento.') });
  const add = useMutation({ mutationFn: (input: Parameters<typeof addQuoteItem>[1]) => addQuoteItem(id, input), onSuccess: () => void client.invalidateQueries({ queryKey: ['quote', id] }) });
  const remove = useMutation({ mutationFn: (itemId: string) => removeQuoteItem(id, itemId), onSuccess: () => void client.invalidateQueries({ queryKey: ['quote', id] }) });
  const update = useMutation({ mutationFn: ({ item, input }: { item: any; input: any }) => updateQuoteItem(id, item.id, input), onSuccess: () => void client.invalidateQueries({ queryKey: ['quote', id] }) });
  const conversion = useMutation({ mutationFn: () => convertQuote(id), onSuccess: (wo) => navigate(`/app/work-orders/${wo.id}`, { state: { saved: 'Orçamento convertido em ordem de serviço.' } }), onError: () => setFeedback('Não foi possível converter o orçamento em ordem de serviço.') });
  if (query.isPending) return <div role="status">Carregando orçamento…</div>;
  if (query.isError || !query.data) return <div role="alert">Orçamento não encontrado.</div>;
  const q = query.data;
  const editable = q.status === 'DRAFT';
  return <><BackLink to="/app/quotes">Voltar para Orçamentos</BackLink><div className="mb-6 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Orçamento #{q.number}</h1><p className="mt-2"><Status value={q.status} /></p></div><div className="flex flex-wrap gap-2">{q.status === 'DRAFT' && <button onClick={() => action.mutate('submit')} className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Enviar para aprovação</button>}{q.status === 'PENDING' && <><button onClick={() => action.mutate('approve')} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Aprovar</button><button onClick={() => action.mutate('reject')} className="rounded-xl border px-3 py-2 text-sm font-semibold">Rejeitar</button></>}{q.status === 'APPROVED' && <button onClick={() => conversion.mutate()} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Gerar ordem de serviço</button>}{['DRAFT', 'PENDING'].includes(q.status) && <button onClick={() => action.mutate('cancel')} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Cancelar</button>}</div></div>{feedback && <p role="status" className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{feedback}</p>}<div className="space-y-5"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Itens do orçamento</h2><ItemsTable items={q.items} editable={editable} onUpdate={(item, input) => update.mutateAsync({ item, input })} onRemove={(itemId) => remove.mutateAsync(itemId)} /><div className="mt-5 border-t pt-4 text-right text-lg font-bold">Total: {money(q.total)}</div></section>{editable && <ItemEditor onAdd={(input) => add.mutateAsync(input)} submitting={add.isPending} />}<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Observações</h2><p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{q.notes || 'Nenhuma observação.'}</p></section></div></>;
}
