import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ApiError } from '@/shared/api/http';
import { money, Status } from '@/features/shared/document-components';
import { getWorkOrder, listWorkOrders } from '@/features/work-orders/api/work-orders-api';
import { cancelPayment, createPayment, listPayments, type FinancialState, type Payment, type PaymentInput } from '../api/payments-api';
import { PaymentForm } from '../components/payment-form';

const methodLabels: Record<string, string> = { CASH: 'Dinheiro', PIX: 'PIX', CREDIT_CARD: 'Cartão de crédito', DEBIT_CARD: 'Cartão de débito', BANK_TRANSFER: 'Transferência bancária', OTHER: 'Outro' };
const paymentStatusLabels: Record<string, string> = { PENDING: 'Pendente', CONFIRMED: 'Confirmado', CANCELLED: 'Cancelado' };
const financialLabels: Record<string, string> = { UNPAID: 'Não pago', PARTIAL: 'Parcial', PAID: 'Pago' };
const date = (value: string | null) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const errorMessage = (error: unknown) => error instanceof ApiError && error.problem.code === 'WORK_ORDER_CANCELLED' ? 'Ordens canceladas não podem receber pagamentos.' : error instanceof ApiError && error.problem.code === 'PAYMENT_EXCEEDS_BALANCE' ? 'O pagamento excede o saldo da ordem.' : 'Não foi possível concluir a operação.';

function FinancialSummary({ financial }: { financial: FinancialState }) { return <section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-4"><div><p className="text-xs font-semibold uppercase text-slate-500">Total</p><p className="mt-1 text-lg font-bold">{money(financial.total)}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Recebido</p><p className="mt-1 text-lg font-bold">{money(financial.paid)}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Saldo</p><p className="mt-1 text-lg font-bold">{money(financial.balance)}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Estado financeiro</p><p className="mt-2"><Status value={financialLabels[financial.status] ?? financial.status} /></p></div></section>; }

function PaymentRow({ payment, onCancel, cancelling }: { payment: Payment; onCancel: () => void; cancelling: boolean }) { return <tr><td className="px-3 py-4 font-semibold">{money(payment.amount)}</td><td className="px-3 py-4">{methodLabels[payment.method] ?? payment.method}</td><td className="px-3 py-4">{paymentStatusLabels[payment.status] ?? payment.status}</td><td className="px-3 py-4">{date(payment.paidAt)}</td><td className="px-3 py-4">{date(payment.createdAt)}</td><td className="px-3 py-4 text-right">{payment.status !== 'CANCELLED' && <button disabled={cancelling} onClick={onCancel} className="font-semibold text-red-600">Cancelar</button>}</td></tr>; }

export function FinancePage() {
  const { workOrderId = '' } = useParams(); const client = useQueryClient(); const [feedback, setFeedback] = useState('');
  const order = useQuery({ queryKey: ['work-order', workOrderId], queryFn: () => getWorkOrder(workOrderId) });
  const payments = useQuery({ queryKey: ['payments', workOrderId], queryFn: () => listPayments(workOrderId), enabled: Boolean(order.data && order.data.status !== 'CANCELLED') });
  const create = useMutation({ mutationFn: (input: PaymentInput) => createPayment(workOrderId, input), onSuccess: async () => { setFeedback('Pagamento registrado.'); await client.invalidateQueries({ queryKey: ['payments', workOrderId] }); } });
  const cancel = useMutation({ mutationFn: (paymentId: string) => cancelPayment(workOrderId, paymentId), onSuccess: async () => { setFeedback('Pagamento cancelado e preservado no histórico.'); await client.invalidateQueries({ queryKey: ['payments', workOrderId] }); } });
  if (order.isPending || (payments.isPending && order.data?.status !== 'CANCELLED')) return <div role="status">Carregando financeiro…</div>; if (order.isError || !order.data || (order.data.status !== 'CANCELLED' && (payments.isError || !payments.data))) return <div role="alert">Não foi possível carregar os pagamentos.</div>;
  const financial = payments.data?.financial ?? { total: order.data.total, paid: '0.00', balance: order.data.total, status: 'UNPAID' as const }; const paymentRows = payments.data?.data ?? [];
  return <div className="mx-auto max-w-6xl"><Link to={`/app/work-orders/${workOrderId}`} className="mb-5 inline-flex text-sm font-semibold text-blue-700">← Voltar para Ordem de Serviço</Link><div className="mb-6"><h1 className="text-2xl font-bold">Financeiro da OS #{order.data.number}</h1><p className="mt-1 text-sm text-slate-500">Registre recebimentos sem alterar o ciclo de entrega da ordem.</p><p className="mt-2"><Status value={order.data.status} /></p></div>{feedback && <p role="status" className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{feedback}</p>}{(create.isError || cancel.isError) && <p role="alert" className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{errorMessage(create.error ?? cancel.error)}</p>}{order.data.status === 'CANCELLED' && <p role="note" className="mb-5 rounded-xl bg-slate-100 p-3 text-sm text-slate-700">Esta ordem está cancelada e não pode receber novos pagamentos.</p>}<div className="space-y-5"><FinancialSummary financial={financial} />{order.data.status !== 'CANCELLED' && <PaymentForm submitting={create.isPending} onSubmit={(input) => create.mutateAsync(input)} />}<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Histórico de pagamentos</h2>{paymentRows.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">Nenhum pagamento registrado.</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Valor</th><th className="px-3 py-3">Método</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Pago em</th><th className="px-3 py-3">Criado em</th><th /></tr></thead><tbody className="divide-y">{paymentRows.map((payment) => <PaymentRow key={payment.id} payment={payment} cancelling={cancel.isPending} onCancel={() => cancel.mutate(payment.id)} />)}</tbody></table></div>}</section></div></div>;
}

export const WorkOrderFinancePage = FinancePage;

export function FinanceIndexPage() {
  const orders = useQuery({ queryKey: ['finance-work-orders'], queryFn: () => listWorkOrders({ page: 1, pageSize: 100, sort: 'createdAt', direction: 'desc' }) });
  if (orders.isPending) return <div role="status">Carregando ordens para o financeiro…</div>;
  if (orders.isError || !orders.data) return <div role="alert">Não foi possível carregar as ordens para o financeiro.</div>;
  return <div className="mx-auto max-w-5xl"><div className="mb-6"><h1 className="text-2xl font-bold">Financeiro</h1><p className="mt-1 text-sm text-slate-500">Selecione uma Work Order para consultar recebimentos e saldo.</p></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Work Orders</h2>{orders.data.data.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">Nenhuma Work Order disponível.</p> : <div className="mt-4 divide-y">{orders.data.data.map((order) => <Link key={order.id} to={`/app/finance/work-orders/${order.id}`} className="flex items-center justify-between gap-4 px-2 py-4 hover:bg-slate-50"><span className="font-medium">Work Order #{order.number}</span><span className="text-sm text-blue-700">Ver financeiro →</span></Link>)}</div>}</section></div>;
}
