import { useEffect, useState } from 'react';
import type { Customer } from '@/features/customers/api/customers-api';
import type { VehicleInput } from '../api/vehicles-api';
import { ApiError } from '@/shared/api/http';

const inputClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none ring-blue-500 placeholder:text-slate-400 focus:ring-2';
type VehicleFormInitial = { customerId?: string | null; plate?: string | null; brand?: string | null; model?: string | null; year?: number | null; color?: string | null; mileage?: number | null; notes?: string | null };
type Props = { customers: Customer[]; initial?: VehicleFormInitial; submitting: boolean; onSubmit: (value: VehicleInput) => Promise<unknown>; onCancel: () => void };

export function VehicleForm({ customers, initial, submitting, onSubmit, onCancel }: Props) {
  const [values, setValues] = useState({ customerId: initial?.customerId ?? '', plate: initial?.plate ?? '', brand: initial?.brand ?? '', model: initial?.model ?? '', year: initial?.year?.toString() ?? '', color: initial?.color ?? '', mileage: initial?.mileage?.toString() ?? '', notes: initial?.notes ?? '' });
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { setValues({ customerId: initial?.customerId ?? '', plate: initial?.plate ?? '', brand: initial?.brand ?? '', model: initial?.model ?? '', year: initial?.year?.toString() ?? '', color: initial?.color ?? '', mileage: initial?.mileage?.toString() ?? '', notes: initial?.notes ?? '' }); }, [initial?.customerId, initial?.plate, initial?.brand, initial?.model, initial?.year, initial?.color, initial?.mileage, initial?.notes]);
  function set(field: keyof typeof values, value: string) { setValues((current) => ({ ...current, [field]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); if (!values.customerId || !values.plate.trim() || !values.brand.trim() || !values.model.trim()) { setError('Preencha cliente, placa, marca e modelo.'); return; } try { await onSubmit({ customerId: values.customerId, plate: values.plate.trim(), brand: values.brand.trim(), model: values.model.trim(), ...(values.year ? { year: Number(values.year) } : {}), ...(values.color.trim() ? { color: values.color.trim() } : {}), ...(values.mileage ? { mileage: Number(values.mileage) } : {}), ...(values.notes.trim() ? { notes: values.notes.trim() } : {}) }); } catch (cause) { setError(cause instanceof ApiError && cause.problem.code === 'CONFLICT' ? 'Já existe um veículo com esta placa.' : 'Não foi possível salvar o veículo.'); } }
  return <form className="space-y-6" onSubmit={submit}>{error && <p role="alert" className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700 sm:col-span-2">Cliente<select aria-label="Cliente" className={`${inputClass} mt-2`} value={values.customerId} onChange={(e) => set('customerId', e.target.value)} required><option value="">Selecione um cliente</option>{customers.filter((customer) => customer.active || customer.id === values.customerId).map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><Field label="Placa" value={values.plate} onChange={(value) => set('plate', value)} required placeholder="ABC-1D23" /><Field label="Marca" value={values.brand} onChange={(value) => set('brand', value)} required placeholder="Toyota" /><Field label="Modelo" value={values.model} onChange={(value) => set('model', value)} required placeholder="Corolla" /><Field label="Ano" type="number" value={values.year} onChange={(value) => set('year', value)} min="1886" max="2500" /><Field label="Cor" value={values.color} onChange={(value) => set('color', value)} /><Field label="Quilometragem" type="number" value={values.mileage} onChange={(value) => set('mileage', value)} min="0" /><label className="text-sm font-medium text-slate-700 sm:col-span-2">Observações<textarea className={`${inputClass} mt-2 min-h-28`} value={values.notes} onChange={(e) => set('notes', e.target.value)} maxLength={2000} /></label></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={onCancel} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancelar</button><button type="submit" disabled={submitting} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{submitting ? 'Salvando…' : 'Salvar veículo'}</button></div></form>;
}
function Field({ label, value, onChange, type = 'text', required, placeholder, min, max }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; placeholder?: string; min?: string; max?: string }) { return <label className="text-sm font-medium text-slate-700">{label}<input className={`${inputClass} mt-2`} type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} placeholder={placeholder} min={min} max={max} /></label>; }
