import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { AuthenticatedPrincipal } from '../auth/authenticated-principal';
import { PrismaService } from '../prisma/prisma.service';
import { CreatePurchaseDto, UpdatePurchaseDto } from './dto/create-purchase.dto';
import { ListPurchasesDto } from './dto/list-purchases.dto';

const cents = (v: string): bigint => { const [w, f = ''] = v.toString().split('.'); return BigInt(w) * 100n + BigInt((f + '00').slice(0, 2)); };
const money = (v: bigint): string => `${v / 100n}.${(v % 100n).toString().padStart(2, '0')}`;
function present(row: any) { const total = (row.items ?? []).reduce((s: bigint, i: any) => s + cents(i.unitCost.toString()) * BigInt(i.quantity), 0n); return { ...row, total: money(total), purchaseDate: row.purchaseDate.toISOString().slice(0, 10), dueDate: row.dueDate.toISOString().slice(0, 10), items: row.items?.map((i: any) => ({ ...i, unitCost: money(cents(i.unitCost.toString())) })) }; }

@Injectable()
export class PurchasesService {
  constructor(private readonly prisma: PrismaService) {}
  private tenant(p: AuthenticatedPrincipal) { if (p.role !== 'ADMIN' || !p.organizationId) throw new ForbiddenException('Organization Admin access required'); return p.organizationId; }
  private include = { supplier: { select: { id: true, name: true } }, items: true, expense: { include: { payments: true } }, stockEntries: true } as const;

  async create(p: AuthenticatedPrincipal, dto: CreatePurchaseDto) {
    const organizationId = this.tenant(p); if (!dto.items.length) throw new ConflictException('Purchase must have at least one item');
    const supplier = await this.prisma.supplier.findFirst({ where: { id: dto.supplierId, organizationId, active: true } }); if (!supplier) throw new NotFoundException('Supplier not found');
    const products = await this.prisma.product.findMany({ where: { organizationId, id: { in: dto.items.map(i => i.productId) }, active: true }, select: { id: true, name: true, sku: true } });
    if (products.length !== new Set(dto.items.map(i => i.productId)).size) throw new NotFoundException('Product not found');
    return present(await this.prisma.$transaction(async (tx) => {
      const purchase = await tx.purchase.create({ data: { organizationId, supplierId: dto.supplierId, purchaseDate: new Date(dto.purchaseDate), dueDate: new Date(dto.dueDate), documentNumber: dto.documentNumber?.trim(), notes: dto.notes?.trim() } });
      await tx.purchaseItem.createMany({ data: dto.items.map(i => { const product = products.find(x => x.id === i.productId)!; return { organizationId, purchaseId: purchase.id, productId: i.productId, productName: product.name, sku: product.sku, quantity: i.quantity, unitCost: i.unitCost, warrantyDays: i.warrantyDays ?? 0, batchNumber: i.batchNumber?.trim() }; }) });
      return tx.purchase.findFirstOrThrow({ where: { id: purchase.id, organizationId }, include: this.include });
    }));
  }
  async list(p: AuthenticatedPrincipal, q: ListPurchasesDto) { const organizationId = this.tenant(p); const page = q.page ?? 1, pageSize = q.pageSize ?? 20; const where: Prisma.PurchaseWhereInput = { organizationId, ...(q.status ? { status: q.status as any } : {}), ...(q.supplierId ? { supplierId: q.supplierId } : {}), ...(q.purchaseDateFrom || q.purchaseDateTo ? { purchaseDate: { ...(q.purchaseDateFrom ? { gte: new Date(q.purchaseDateFrom) } : {}), ...(q.purchaseDateTo ? { lte: new Date(q.purchaseDateTo) } : {}) } } : {}) }; const [rows, total] = await this.prisma.$transaction([this.prisma.purchase.findMany({ where, include: this.include, orderBy: [{ purchaseDate: 'desc' }, { id: 'desc' }], skip: (page - 1) * pageSize, take: pageSize }), this.prisma.purchase.count({ where })]); return { data: rows.map(present), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findOne(p: AuthenticatedPrincipal, id: string) { const row = await this.prisma.purchase.findFirst({ where: { id, organizationId: this.tenant(p) }, include: this.include }); if (!row) throw new NotFoundException('Purchase not found'); return present(row); }
  async update(p: AuthenticatedPrincipal, id: string, dto: UpdatePurchaseDto) { const organizationId = this.tenant(p); return present(await this.prisma.$transaction(async tx => { const current = await tx.purchase.findFirst({ where: { id, organizationId }, include: { items: true } }); if (!current) throw new NotFoundException('Purchase not found'); if (current.status !== 'DRAFT') throw new ConflictException('Only draft Purchases can be edited'); const supplier = await tx.supplier.findFirst({ where: { id: dto.supplierId, organizationId, active: true } }); if (!supplier) throw new NotFoundException('Supplier not found'); const products = await tx.product.findMany({ where: { organizationId, id: { in: dto.items.map(i => i.productId) }, active: true }, select: { id: true, name: true, sku: true } }); if (products.length !== new Set(dto.items.map(i => i.productId)).size) throw new NotFoundException('Product not found'); await tx.purchaseItem.deleteMany({ where: { purchaseId: id, organizationId } }); await tx.purchaseItem.createMany({ data: dto.items.map(i => { const product = products.find(x => x.id === i.productId)!; return { organizationId, purchaseId: id, productId: i.productId, productName: product.name, sku: product.sku, quantity: i.quantity, unitCost: i.unitCost, warrantyDays: i.warrantyDays ?? 0, batchNumber: i.batchNumber?.trim() }; }) }); return tx.purchase.findFirstOrThrow({ where: { organizationId, id }, include: this.include }); })); }
  async confirm(p: AuthenticatedPrincipal, id: string) { const organizationId = this.tenant(p); const row = await this.prisma.$transaction(async tx => { const purchase = await tx.purchase.findFirst({ where: { id, organizationId }, include: { items: true } }); if (!purchase) throw new NotFoundException('Purchase not found'); if (purchase.status !== 'DRAFT') throw new ConflictException('Only draft Purchases can be confirmed'); const total = purchase.items.reduce((s, i) => s + cents(i.unitCost.toString()) * BigInt(i.quantity), 0n); const expense = await tx.expense.create({ data: { organizationId, category: 'PARTS_AND_SUPPLIES', description: `Compra do fornecedor ${purchase.supplierId}`, amount: new Prisma.Decimal(money(total)), dueDate: purchase.dueDate } }); await tx.expensePayment.create({ data: { organizationId, expenseId: expense.id, amount: new Prisma.Decimal(money(total)), method: 'OTHER', status: 'CONFIRMED', paidAt: purchase.dueDate } }); for (const item of purchase.items) { await tx.product.update({ where: { organizationId_id: { organizationId, id: item.productId } }, data: { stockQuantity: { increment: item.quantity } } }); await tx.stockEntry.create({ data: { organizationId, purchaseId: id, purchaseItemId: item.id, productId: item.productId, supplierId: purchase.supplierId, quantity: item.quantity, unitCost: item.unitCost, purchaseDate: purchase.purchaseDate, batchNumber: item.batchNumber, documentNumber: purchase.documentNumber, warrantyDays: item.warrantyDays } }); } return tx.purchase.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CONFIRMED', expenseId: expense.id, confirmedAt: new Date() }, include: this.include }); }); return present(row); }
  async cancel(p: AuthenticatedPrincipal, id: string) { const organizationId = this.tenant(p); return present(await this.prisma.$transaction(async tx => { const purchase = await tx.purchase.findFirst({ where: { id, organizationId }, include: { stockEntries: true, expense: { include: { payments: true } } } }); if (!purchase) throw new NotFoundException('Purchase not found'); if (purchase.status === 'CANCELLED') throw new ConflictException('Purchase is already cancelled'); if (purchase.status === 'DRAFT') return tx.purchase.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CANCELLED' }, include: this.include }); if (purchase.stockEntries.some(e => e.consumedQuantity > 0)) throw new ConflictException('Purchase entries already have consumed stock'); if (purchase.expense?.payments.some(x => x.status === 'CONFIRMED')) throw new ConflictException('Purchase Expense has confirmed payments'); for (const entry of purchase.stockEntries) { await tx.product.update({ where: { organizationId_id: { organizationId, id: entry.productId } }, data: { stockQuantity: { decrement: entry.quantity } } }); await tx.stockEntry.update({ where: { id: entry.id }, data: { status: 'CANCELLED' } }); } if (purchase.expenseId) await tx.expense.update({ where: { id: purchase.expenseId }, data: { status: 'CANCELLED' } }); return tx.purchase.update({ where: { organizationId_id: { organizationId, id } }, data: { status: 'CANCELLED' }, include: this.include }); })); }
}
